// Curated Hangul gallery — popular names, K-pop idols, and beloved Korean words.
// Each entry's `text` is the exact Hangul that gets fed to the Hangul Art renderer.
// `sub` (optional) is shown beneath as a small caption (English/romanization/credit).

export interface GalleryItem {
  text: string;
  sub?: string;
}

export interface GalleryCategory {
  id: string;
  labelKo: string;
  labelEn: string;
  emoji: string;
  items: GalleryItem[];
}

export const GALLERY: GalleryCategory[] = [
  {
    id: "bts",
    labelKo: "BTS",
    labelEn: "BTS",
    emoji: "💜",
    items: [
      { text: "정국",   sub: "Jungkook" },
      { text: "지민",   sub: "Jimin" },
      { text: "뷔",     sub: "V" },
      { text: "진",     sub: "Jin" },
      { text: "슈가",   sub: "Suga" },
      { text: "제이홉", sub: "J-Hope" },
      { text: "알엠",   sub: "RM" },
      { text: "태형",   sub: "Taehyung" },
    ],
  },
  {
    id: "blackpink",
    labelKo: "BLACKPINK",
    labelEn: "BLACKPINK",
    emoji: "🖤",
    items: [
      { text: "지수",   sub: "Jisoo" },
      { text: "제니",   sub: "Jennie" },
      { text: "로제",   sub: "Rosé" },
      { text: "리사",   sub: "Lisa" },
    ],
  },
  {
    id: "newjeans",
    labelKo: "NewJeans",
    labelEn: "NewJeans",
    emoji: "🐰",
    items: [
      { text: "민지",   sub: "Minji" },
      { text: "하니",   sub: "Hanni" },
      { text: "다니엘", sub: "Danielle" },
      { text: "혜린",   sub: "Haerin" },
      { text: "혜인",   sub: "Hyein" },
    ],
  },
  {
    id: "aespa",
    labelKo: "aespa",
    labelEn: "aespa",
    emoji: "🦋",
    items: [
      { text: "카리나", sub: "Karina" },
      { text: "윈터",   sub: "Winter" },
      { text: "지젤",   sub: "Giselle" },
      { text: "닝닝",   sub: "Ningning" },
    ],
  },
  {
    id: "ive",
    labelKo: "IVE",
    labelEn: "IVE",
    emoji: "✨",
    items: [
      { text: "장원영", sub: "Wonyoung" },
      { text: "안유진", sub: "Yujin" },
      { text: "가을",   sub: "Gaeul" },
      { text: "리즈",   sub: "Liz" },
      { text: "이서",   sub: "Leeseo" },
      { text: "레이",   sub: "Rei" },
    ],
  },
  {
    id: "twice",
    labelKo: "TWICE",
    labelEn: "TWICE",
    emoji: "🍭",
    items: [
      { text: "나연",   sub: "Nayeon" },
      { text: "정연",   sub: "Jeongyeon" },
      { text: "모모",   sub: "Momo" },
      { text: "사나",   sub: "Sana" },
      { text: "지효",   sub: "Jihyo" },
      { text: "미나",   sub: "Mina" },
      { text: "다현",   sub: "Dahyun" },
      { text: "채영",   sub: "Chaeyoung" },
      { text: "쯔위",   sub: "Tzuyu" },
    ],
  },
  {
    id: "snsd",
    labelKo: "소녀시대",
    labelEn: "Girls' Generation",
    emoji: "👑",
    items: [
      { text: "태연",   sub: "Taeyeon" },
      { text: "윤아",   sub: "YoonA" },
      { text: "수영",   sub: "Sooyoung" },
      { text: "티파니", sub: "Tiffany" },
      { text: "써니",   sub: "Sunny" },
    ],
  },
  {
    id: "exo",
    labelKo: "EXO",
    labelEn: "EXO",
    emoji: "⭐",
    items: [
      { text: "세훈",   sub: "Sehun" },
      { text: "카이",   sub: "Kai" },
      { text: "백현",   sub: "Baekhyun" },
      { text: "찬열",   sub: "Chanyeol" },
      { text: "디오",   sub: "D.O." },
      { text: "수호",   sub: "Suho" },
    ],
  },
  {
    id: "other-idols",
    labelKo: "기타 아이돌",
    labelEn: "Other Idols",
    emoji: "🎤",
    items: [
      { text: "루카",   sub: "ZEROBASEONE" },
      { text: "한빈",   sub: "ZEROBASEONE" },
      { text: "규빈",   sub: "ZEROBASEONE" },
      { text: "니키",   sub: "ENHYPEN" },
      { text: "선우",   sub: "ENHYPEN" },
      { text: "제이크", sub: "ENHYPEN" },
      { text: "로운",   sub: "SF9" },
      { text: "아이유", sub: "IU" },
      { text: "수지",   sub: "Suzy" },
    ],
  },
  {
    id: "actors",
    labelKo: "배우",
    labelEn: "Actors",
    emoji: "🎬",
    items: [
      { text: "박보검", sub: "Park Bo-gum" },
      { text: "송중기", sub: "Song Joong-ki" },
      { text: "현빈",   sub: "Hyun Bin" },
      { text: "손예진", sub: "Son Ye-jin" },
    ],
  },
  {
    id: "names-ㄱㄴㄷ",
    labelKo: "이름 ㄱ-ㄷ",
    labelEn: "Names ㄱ-ㄷ",
    emoji: "👶",
    items: [
      { text: "가을",   sub: "Ga-eul" },
      { text: "나은",   sub: "Na-eun" },
      { text: "다은",   sub: "Da-eun" },
      { text: "다현",   sub: "Da-hyun" },
      { text: "도윤",   sub: "Do-yoon" },
    ],
  },
  {
    id: "names-ㄹㅁㅂ",
    labelKo: "이름 ㄹ-ㅂ",
    labelEn: "Names ㄹ-ㅂ",
    emoji: "👶",
    items: [
      { text: "민준",   sub: "Min-jun" },
      { text: "민서",   sub: "Min-seo" },
      { text: "민재",   sub: "Min-jae" },
      { text: "민우",   sub: "Min-woo" },
      { text: "민주",   sub: "Min-ju" },
    ],
  },
  {
    id: "names-ㅅㅇ",
    labelKo: "이름 ㅅ-ㅇ",
    labelEn: "Names ㅅ-ㅇ",
    emoji: "👶",
    items: [
      { text: "서연",   sub: "Seo-yeon" },
      { text: "서준",   sub: "Seo-jun" },
      { text: "서우",   sub: "Seo-woo" },
      { text: "선우",   sub: "Seon-woo" },
      { text: "시우",   sub: "Si-woo" },
      { text: "시윤",   sub: "Si-yoon" },
      { text: "시현",   sub: "Si-hyun" },
      { text: "수아",   sub: "Su-a" },
      { text: "수빈",   sub: "Su-bin" },
      { text: "소윤",   sub: "So-yoon" },
      { text: "소연",   sub: "So-yeon" },
      { text: "승현",   sub: "Seung-hyun" },
      { text: "아린",   sub: "A-rin" },
      { text: "안유진", sub: "An Yu-jin" },
      { text: "연우",   sub: "Yeon-woo" },
      { text: "예준",   sub: "Ye-jun" },
      { text: "예은",   sub: "Ye-eun" },
      { text: "예진",   sub: "Ye-jin" },
      { text: "윤서",   sub: "Yoon-seo" },
      { text: "유나",   sub: "Yu-na" },
      { text: "유진",   sub: "Yu-jin" },
      { text: "은우",   sub: "Eun-woo" },
      { text: "은서",   sub: "Eun-seo" },
    ],
  },
  {
    id: "names-ㅈㅊㅌㅎ",
    labelKo: "이름 ㅈ-ㅎ",
    labelEn: "Names ㅈ-ㅎ",
    emoji: "👶",
    items: [
      { text: "재윤",   sub: "Jae-yoon" },
      { text: "주원",   sub: "Ju-won" },
      { text: "준서",   sub: "Jun-seo" },
      { text: "준혁",   sub: "Jun-hyuk" },
      { text: "준영",   sub: "Jun-young" },
      { text: "지우",   sub: "Ji-woo" },
      { text: "지호",   sub: "Ji-ho" },
      { text: "지안",   sub: "Ji-an" },
      { text: "지훈",   sub: "Ji-hoon" },
      { text: "지유",   sub: "Ji-yu" },
      { text: "채원",   sub: "Chae-won" },
      { text: "태윤",   sub: "Tae-yoon" },
      { text: "태희",   sub: "Tae-hee" },
      { text: "하윤",   sub: "Ha-yoon" },
      { text: "하준",   sub: "Ha-jun" },
      { text: "하은",   sub: "Ha-eun" },
      { text: "현우",   sub: "Hyun-woo" },
    ],
  },
  {
    id: "onomatopoeia",
    labelKo: "의성어·의태어",
    labelEn: "Sound & Mimetic Words",
    emoji: "💫",
    items: [
      { text: "반짝반짝", sub: "twinkle twinkle" },
      { text: "두근두근", sub: "pit-a-pat" },
      { text: "콩닥콩닥", sub: "thump thump" },
      { text: "졸졸", sub: "babble" },
      { text: "쏴아", sub: "whoosh" },
      { text: "쨍쨍", sub: "bright" },
      { text: "활짝", sub: "wide open" },
      { text: "깜짝", sub: "startle" },
      { text: "펄럭", sub: "flutter" },
      { text: "살랑살랑", sub: "softly" },
      { text: "부슬부슬", sub: "drizzle" },
      { text: "주룩주룩", sub: "pour" },
      { text: "쿵쿵", sub: "thud thud" },
      { text: "딸랑딸랑", sub: "jingle" },
      { text: "하하", sub: "ha ha" },
      { text: "호호", sub: "ho ho" },
      { text: "킥킥", sub: "giggle" },
      { text: "엉엉", sub: "sob" },
      { text: "칭얼", sub: "whine" },
      { text: "폴짝폴짝", sub: "hop hop" },
      { text: "데굴데굴", sub: "roll roll" },
      { text: "동동", sub: "stamp stamp" },
      { text: "아장아장", sub: "toddle" },
      { text: "아삭아삭", sub: "crispy" },
      { text: "쫄깃쫄깃", sub: "chewy" },
      { text: "보글보글", sub: "bubble" },
      { text: "치직", sub: "sizzle" },
      { text: "빙글빙글", sub: "spin spin" },
      { text: "살금살금", sub: "sneak" },
      { text: "폴짝", sub: "hop" },
    ],
  },
  {
    id: "words-nature",
    labelKo: "자연 단어",
    labelEn: "Nature Words",
    emoji: "🌿",
    items: [
      { text: "하늘",   sub: "sky" },
      { text: "바다",   sub: "sea" },
      { text: "구름",   sub: "cloud" },
      { text: "바람",   sub: "wind" },
      { text: "눈",     sub: "snow" },
      { text: "비",     sub: "rain" },
      { text: "산",     sub: "mountain" },
      { text: "강",     sub: "river" },
      { text: "숲",     sub: "forest" },
      { text: "섬",     sub: "island" },
      { text: "해",     sub: "sun" },
      { text: "달",     sub: "moon" },
      { text: "별",     sub: "star" },
      { text: "물",     sub: "water" },
      { text: "불",     sub: "fire" },
      { text: "흙",     sub: "earth" },
      { text: "돌",     sub: "stone" },
      { text: "모래",   sub: "sand" },
      { text: "파도",   sub: "wave" },
      { text: "무지개", sub: "rainbow" },
      { text: "이슬",   sub: "dew" },
      { text: "서리",   sub: "frost" },
      { text: "안개",   sub: "fog" },
      { text: "천둥",   sub: "thunder" },
      { text: "번개",   sub: "lightning" },
    ],
  },
  {
    id: "words-flora",
    labelKo: "꽃과 나무",
    labelEn: "Flowers & Trees",
    emoji: "🌸",
    items: [
      { text: "꽃",       sub: "flower" },
      { text: "매화",     sub: "plum blossom" },
      { text: "난초",     sub: "orchid" },
      { text: "국화",     sub: "chrysanthemum" },
      { text: "연꽃",     sub: "lotus" },
      { text: "장미",     sub: "rose" },
      { text: "백합",     sub: "lily" },
      { text: "해바라기", sub: "sunflower" },
      { text: "민들레",   sub: "dandelion" },
      { text: "나무",     sub: "tree" },
      { text: "소나무",   sub: "pine tree" },
      { text: "대나무",   sub: "bamboo" },
    ],
  },
  {
    id: "words-animals",
    labelKo: "동물",
    labelEn: "Animals",
    emoji: "🦋",
    items: [
      { text: "나비",     sub: "butterfly" },
      { text: "잠자리",   sub: "dragonfly" },
      { text: "반딧불",   sub: "firefly" },
      { text: "새",       sub: "bird" },
      { text: "학",       sub: "crane" },
      { text: "고래",     sub: "whale" },
      { text: "돌고래",   sub: "dolphin" },
      { text: "호랑이",   sub: "tiger" },
      { text: "용",       sub: "dragon" },
    ],
  },
  {
    id: "words-treasures",
    labelKo: "보석",
    labelEn: "Treasures",
    emoji: "💎",
    items: [
      { text: "금",   sub: "gold" },
      { text: "은",   sub: "silver" },
      { text: "옥",   sub: "jade" },
      { text: "진주", sub: "pearl" },
    ],
  },
  {
    id: "words-abstract",
    labelKo: "추상 단어",
    labelEn: "Abstract Words",
    emoji: "✨",
    items: [
      { text: "꿈",   sub: "dream" },
      { text: "복",   sub: "blessing" },
      { text: "빛",   sub: "light" },
      { text: "봄",   sub: "spring" },
      { text: "맘",   sub: "heart" },
      { text: "춤",   sub: "dance" },
      { text: "삶",   sub: "life" },
      { text: "정",   sub: "affection" },
      { text: "길",   sub: "road" },
      { text: "집",   sub: "home" },
    ],
  },
  {
    id: "phrases",
    labelKo: "K-드라마 단어",
    labelEn: "K-Drama Words",
    emoji: "💬",
    items: [
      { text: "안녕",   sub: "Hello / Bye" },
      { text: "사랑",   sub: "Love" },
      { text: "행복",   sub: "Happiness" },
      { text: "감사",   sub: "Thanks" },
      { text: "친구",   sub: "Friend" },
      { text: "화이팅", sub: "Cheer up!" },
      { text: "오빠",   sub: "Oppa" },
      { text: "언니",   sub: "Unnie" },
      { text: "한국",   sub: "Korea" },
      { text: "서울",   sub: "Seoul" },
      { text: "김치",   sub: "Kimchi" },
      { text: "한글",   sub: "Hangul" },
      { text: "고마워", sub: "Thank you" },
      { text: "미안해", sub: "Sorry" },
      { text: "괜찮아", sub: "It's okay" },
      { text: "사랑해", sub: "I love you" },
      { text: "보고싶어", sub: "I miss you" },
      { text: "잘자",   sub: "Good night" },
      { text: "대박",   sub: "Awesome!" },
      { text: "진짜",   sub: "Really" },
      { text: "이뻐",   sub: "Pretty" },
      { text: "멋져",   sub: "Cool" },
      { text: "귀여워", sub: "Cute" },
      { text: "맛있어", sub: "Delicious" },
      { text: "졸려",   sub: "Sleepy" },
      { text: "배고파", sub: "Hungry" },
      { text: "좋아",   sub: "Good / I like it" },
      { text: "싫어",   sub: "I don't like it" },
      { text: "힘내",   sub: "Cheer up" },
      { text: "사랑스러워", sub: "Lovely" },
      { text: "축하해", sub: "Congrats" },
      { text: "생일",   sub: "Birthday" },
      { text: "웃어",   sub: "Smile" },
      { text: "울어",   sub: "Cry" },
      { text: "웃음",   sub: "Laughter" },
      { text: "눈물",   sub: "Tears" },
      { text: "희망",   sub: "Hope" },
      { text: "용기",   sub: "Courage" },
      { text: "평화",   sub: "Peace" },
      { text: "자유",   sub: "Freedom" },
      { text: "지혜",   sub: "Wisdom" },
      { text: "정의",   sub: "Justice" },
      { text: "진실",   sub: "Truth" },
      { text: "믿음",   sub: "Faith" },
      { text: "열정",   sub: "Passion" },
      { text: "꿈꾸는", sub: "Dreaming" },
      { text: "반짝반짝", sub: "Sparkling" },
      { text: "두근두근", sub: "Heart beating" },
      { text: "설렘",   sub: "Excitement" },
      { text: "추억",   sub: "Memory" },
      { text: "인연",   sub: "Destiny" },
      { text: "운명",   sub: "Fate" },
      { text: "기적",   sub: "Miracle" },
      { text: "영원",   sub: "Eternity" },
      { text: "순간",   sub: "Moment" },
      { text: "함께",   sub: "Together" },
      { text: "약속",   sub: "Promise" },
      { text: "소중해", sub: "Precious" },
      { text: "고맙다", sub: "Grateful" },
    ],
  },
];

export function getAllItems(): GalleryItem[] {
  return GALLERY.flatMap((c) => c.items);
}

export function getCategory(id: string): GalleryCategory | undefined {
  return GALLERY.find((c) => c.id === id);
}
