// Curated Hangul gallery — popular names, K-pop idols, and beloved Korean words.
// Each entry's `text` is the exact Hangul that gets fed to the Hangul Art renderer.
// `sub` (optional) is shown beneath as a small caption (English/romanization/credit).

export interface GalleryItem {
  text: string;
  sub?: string;
}

export interface GalleryCategory {
  id: string;
  labelKo: string;
  labelEn: string;
  emoji: string;
  items: GalleryItem[];
}

export const GALLERY: GalleryCategory[] = [
  {
    id: "kpop",
    labelKo: "K-POP 아이돌",
    labelEn: "K-POP Idols",
    emoji: "🎤",
    items: [
      { text: "정국",   sub: "Jungkook · BTS" },
      { text: "지민",   sub: "Jimin · BTS" },
      { text: "뷔",     sub: "V · BTS" },
      { text: "진",     sub: "Jin · BTS" },
      { text: "슈가",   sub: "Suga · BTS" },
      { text: "제이홉", sub: "J-Hope · BTS" },
      { text: "알엠",   sub: "RM · BTS" },
      { text: "지수",   sub: "Jisoo · BLACKPINK" },
      { text: "제니",   sub: "Jennie · BLACKPINK" },
      { text: "로제",   sub: "Rosé · BLACKPINK" },
      { text: "리사",   sub: "Lisa · BLACKPINK" },
      { text: "민지",   sub: "Minji · NewJeans" },
      { text: "하니",   sub: "Hanni · NewJeans" },
      { text: "다니엘", sub: "Danielle · NewJeans" },
      { text: "혜린",   sub: "Haerin · NewJeans" },
      { text: "혜인",   sub: "Hyein · NewJeans" },
      { text: "카리나", sub: "Karina · aespa" },
      { text: "윈터",   sub: "Winter · aespa" },
      { text: "지젤",   sub: "Giselle · aespa" },
      { text: "닝닝",   sub: "Ningning · aespa" },
      { text: "장원영", sub: "Wonyoung · IVE" },
      { text: "안유진", sub: "Yujin · IVE" },
      { text: "가을",   sub: "Gaeul · IVE" },
      { text: "리즈",   sub: "Liz · IVE" },
      { text: "이서",   sub: "Leeseo · IVE" },
      { text: "레이",   sub: "Rei · IVE" },
      { text: "태연",   sub: "Taeyeon · SNSD" },
      { text: "윤아",   sub: "YoonA · SNSD" },
      { text: "수영",   sub: "Sooyoung · SNSD" },
      { text: "티파니", sub: "Tiffany · SNSD" },
      { text: "써니",   sub: "Sunny · SNSD" },
      { text: "나연",   sub: "Nayeon · TWICE" },
      { text: "정연",   sub: "Jeongyeon · TWICE" },
      { text: "모모",   sub: "Momo · TWICE" },
      { text: "사나",   sub: "Sana · TWICE" },
      { text: "지효",   sub: "Jihyo · TWICE" },
      { text: "미나",   sub: "Mina · TWICE" },
      { text: "다현",   sub: "Dahyun · TWICE" },
      { text: "채영",   sub: "Chaeyoung · TWICE" },
      { text: "쯔위",   sub: "Tzuyu · TWICE" },
      { text: "박보검", sub: "Park Bo-gum" },
      { text: "송중기", sub: "Song Joong-ki" },
      { text: "현빈",   sub: "Hyun Bin" },
      { text: "손예진", sub: "Son Ye-jin" },
      { text: "아이유", sub: "IU" },
      { text: "수지",   sub: "Suzy" },
      { text: "태형",   sub: "Taehyung · BTS" },
      { text: "로운",   sub: "Rowoon · SF9" },
    ],
  },
  {
    id: "classic-names",
    labelKo: "한국 이름",
    labelEn: "Korean Names",
    emoji: "👤",
    items: [
      { text: "민준", sub: "Min-jun" },
      { text: "서연", sub: "Seo-yeon" },
      { text: "지우", sub: "Ji-woo" },
      { text: "예준", sub: "Ye-jun" },
      { text: "하윤", sub: "Ha-yoon" },
      { text: "도윤", sub: "Do-yoon" },
      { text: "시우", sub: "Si-woo" },
      { text: "수아", sub: "Su-a" },
      { text: "지호", sub: "Ji-ho" },
      { text: "은우", sub: "Eun-woo" },
      { text: "유나", sub: "Yu-na" },
      { text: "지안", sub: "Ji-an" },
      { text: "서준", sub: "Seo-jun" },
      { text: "민서", sub: "Min-seo" },
      { text: "하준", sub: "Ha-jun" },
      { text: "지훈", sub: "Ji-hoon" },
      { text: "은서", sub: "Eun-seo" },
      { text: "예은", sub: "Ye-eun" },
      { text: "시윤", sub: "Si-yoon" },
      { text: "주원", sub: "Ju-won" },
      { text: "지유", sub: "Ji-yu" },
      { text: "하은", sub: "Ha-eun" },
      { text: "민재", sub: "Min-jae" },
      { text: "서우", sub: "Seo-woo" },
      { text: "선우", sub: "Seon-woo" },
      { text: "아린", sub: "A-rin" },
      { text: "연우", sub: "Yeon-woo" },
      { text: "재윤", sub: "Jae-yoon" },
      { text: "수빈", sub: "Su-bin" },
      { text: "나은", sub: "Na-eun" },
      { text: "다은", sub: "Da-eun" },
      { text: "채원", sub: "Chae-won" },
      { text: "시현", sub: "Si-hyun" },
      { text: "윤서", sub: "Yoon-seo" },
      { text: "태윤", sub: "Tae-yoon" },
      { text: "준서", sub: "Jun-seo" },
    ],
  },
  {
    id: "words",
    labelKo: "한글 한 글자",
    labelEn: "One-Syllable Words",
    emoji: "✨",
    items: [
      { text: "꽃", sub: "flower" },
      { text: "별", sub: "star" },
      { text: "달", sub: "moon" },
      { text: "꿈", sub: "dream" },
      { text: "복", sub: "blessing" },
      { text: "빛", sub: "light" },
      { text: "봄", sub: "spring" },
      { text: "맘", sub: "heart" },
      { text: "숲", sub: "forest" },
      { text: "춤", sub: "dance" },
      { text: "삶", sub: "life" },
      { text: "정", sub: "affection" },
      { text: "하늘", sub: "sky" },
      { text: "바다", sub: "sea" },
      { text: "구름", sub: "cloud" },
      { text: "바람", sub: "wind" },
      { text: "눈", sub: "snow" },
      { text: "비", sub: "rain" },
      { text: "길", sub: "road" },
      { text: "집", sub: "home" },
      { text: "산", sub: "mountain" },
      { text: "강", sub: "river" },
      { text: "나무", sub: "tree" },
      { text: "돌", sub: "stone" },
      { text: "해", sub: "sun" },
      { text: "섬", sub: "island" },
      { text: "새", sub: "bird" },
      { text: "물", sub: "water" },
      { text: "불", sub: "fire" },
      { text: "흙", sub: "earth" },
      { text: "금", sub: "gold" },
      { text: "은", sub: "silver" },
      { text: "옥", sub: "jade" },
      { text: "진주", sub: "pearl" },
      { text: "무지개", sub: "rainbow" },
      { text: "이슬", sub: "dew" },
      { text: "서리", sub: "frost" },
      { text: "안개", sub: "fog" },
      { text: "천둥", sub: "thunder" },
      { text: "번개", sub: "lightning" },
    ],
  },
  {
    id: "phrases",
    labelKo: "K-드라마 단어",
    labelEn: "K-Drama Words",
    emoji: "💬",
    items: [
      { text: "안녕",   sub: "Hello / Bye" },
      { text: "사랑",   sub: "Love" },
      { text: "행복",   sub: "Happiness" },
      { text: "감사",   sub: "Thanks" },
      { text: "친구",   sub: "Friend" },
      { text: "화이팅", sub: "Cheer up!" },
      { text: "오빠",   sub: "Oppa" },
      { text: "언니",   sub: "Unnie" },
      { text: "한국",   sub: "Korea" },
      { text: "서울",   sub: "Seoul" },
      { text: "김치",   sub: "Kimchi" },
      { text: "한글",   sub: "Hangul" },
      { text: "고마워", sub: "Thank you" },
      { text: "미안해", sub: "Sorry" },
      { text: "괜찮아", sub: "It's okay" },
      { text: "사랑해", sub: "I love you" },
      { text: "보고싶어", sub: "I miss you" },
      { text: "잘자",   sub: "Good night" },
      { text: "대박",   sub: "Awesome!" },
      { text: "진짜",   sub: "Really" },
      { text: "이뻐",   sub: "Pretty" },
      { text: "멋져",   sub: "Cool" },
      { text: "귀여워", sub: "Cute" },
      { text: "맛있어", sub: "Delicious" },
      { text: "졸려",   sub: "Sleepy" },
      { text: "배고파", sub: "Hungry" },
      { text: "좋아",   sub: "Good / I like it" },
      { text: "싫어",   sub: "I don't like it" },
      { text: "힘내",   sub: "Cheer up" },
      { text: "사랑스러워", sub: "Lovely" },
      { text: "축하해", sub: "Congrats" },
      { text: "생일",   sub: "Birthday" },
      { text: "웃어",   sub: "Smile" },
      { text: "울어",   sub: "Cry" },
      { text: "웃음",   sub: "Laughter" },
      { text: "눈물",   sub: "Tears" },
      { text: "희망",   sub: "Hope" },
      { text: "용기",   sub: "Courage" },
      { text: "평화",   sub: "Peace" },
      { text: "자유",   sub: "Freedom" },
    ],
  },
];

export function getAllItems(): GalleryItem[] {
  return GALLERY.flatMap((c) => c.items);
}

export function getCategory(id: string): GalleryCategory | undefined {
  return GALLERY.find((c) => c.id === id);
}
