// Korean onomatopoeia & mimetic words (의성어·의태어). Source: curated sheet.
export interface SoundEntry { cat: string; word: string; romaja: string; ipa: string; descKo: string; descEn: string; exKo: string; exEn: string; en: string; }

export const CAT_EN: Record<string, string> = {"감정/심리":"Emotions/Psychology","동물 소리":"Animal Sounds","말/대화":"Speech/Conversation","맛/냄새":"Taste/Smell","모양/형태":"Shape/Form","빛/색깔":"Light/Color","사람 소리":"Human Sounds","상태/정도":"State/Degree","소리":"Sounds","시선/눈":"Gaze/Eyes","액체/물":"Liquid/Water","움직임/동작":"Movement/Action","음식/식감":"Food/Texture","자연현상":"Natural Phenomena","작업/행위":"Work/Activity","촉감/질감":"Texture/Touch","통증/신체반응":"Pain/Physical Response","기타":"Other"};

const RAW: [string,string,string,string,string,string,string,string,string][] = [
  ["감정/심리","두근두근","dugeundugeun","/duɡɯnduɡɯn/","심장이 두근거리는 소리/느낌","Heart beating fast with excitement","첫사랑에 심장이 두근두근","Heart beats thump thump with first love","thump thump"],
  ["감정/심리","콩닥콩닥","kongdakkongdak","/koŋdak͈oŋdak/","심장이 두근거리는 소리 (작고 빠른)","Heart fluttering quickly","설레는 마음에 콩닥콩닥","Heart flutters pit-a-pat with excitement","pit-a-pat"],
  ["감정/심리","깜짝","kkamjjak","/k͈amtɕ͈ak/","갑자기 놀라는 모양","Being startled suddenly","깜짝 놀랐어요","Was startled suddenly",""],
  ["감정/심리","니글니글","nigeulnigeul","/niɡɯlniɡɯl/","메스꺼운 느낌","Feeling nauseous","속이 니글니글 메스껍다","Feeling nauseous and queasy",""],
  ["감정/심리","둑흔둑흔","dukheundukheun","/dukhɯndukhɯn/","두근두근의 강한 형태","Heart pounding heavily","심장이 둑흔둑흔 뛴다","Heart pounds heavily",""],
  ["감정/심리","무시무시","musimusi","/musimusi/","무섭고 으스스한 느낌","Scary and eerie","귀신이 무시무시하게 나타났다","Ghost appeared scarily",""],
  ["감정/심리","바보바보","babobabo","/babobabo/","바보 같은 모양","Acting foolishly","넌 정말 바보바보야","You're really foolish",""],
  ["감정/심리","아찔아찔","ajjilajjil","/atɕ͈ilatɕ͈il/","어지러운 느낌","Feeling dizzy","높은 곳을 보니 아찔아찔","Feeling dizzy looking down from high",""],
  ["감정/심리","울렁울렁","ulreongulreong","/ulɾʌŋulɾʌŋ/","울렁거리는 모양","Feeling seasick or queasy","뱃멀미로 속이 울렁울렁","Stomach churns with seasickness",""],
  ["감정/심리","헤롱헤롱","herongherong","/heɾoŋheɾoŋ/","정신이 흐릿한 모양","Feeling dazed or dreamy","술에 취해 헤롱헤롱","Dazed from drinking",""],
  ["감정/심리","헬렐레","helrelre","/helɾelɾe/","정신없이 흘린 모양","Being absent-minded","정신없이 헬렐레","Completely absent-minded",""],
  ["동물 소리","멍멍","meongmeong","/mʌŋmʌŋ/","개 짖는 소리","Dog barking sound","강아지가 멍멍 짖는다","The puppy barks woof woof","woof woof / bow wow"],
  ["동물 소리","야옹/냐옹","yaong","/jaoŋ/","고양이 울음소리","Cat meowing sound","고양이가 야옹야옹 운다","The cat meows meow meow","meow"],
  ["동물 소리","음메","eumme","/ɯmme/","소 울음소리","Cow mooing sound","송아지가 음메음메 운다","The calf moos moo moo","moo"],
  ["동물 소리","꼬끼오","kkokkio","/k͈ok͈io/","닭 울음소리","Rooster crowing sound","새벽에 닭이 꼬끼오 운다","The rooster crows cock-a-doodle-doo at dawn","cock-a-doodle-doo"],
  ["동물 소리","개굴개굴","gaegulgaegul","/ɡɛɡulɡɛɡul/","개구리 울음소리","Frog croaking sound","개구리가 개굴개굴 노래한다","The frog croaks ribbit ribbit","ribbit ribbit"],
  ["동물 소리","꿀꿀","kkulkkul","/k͈ulk͈ul/","돼지 울음소리","Pig oinking sound","돼지가 꿀꿀 운다","The pig oinks oink oink","oink oink"],
  ["동물 소리","삐약삐약","ppiyakppiyak","/p͈ijakp͈ijak/","병아리 울음소리","Chick chirping sound","병아리가 삐약삐약 따라온다","The chicks follow chirping cheep cheep","cheep cheep / peep peep"],
  ["동물 소리","짹짹","jjaekjjaek","/tɕ͈ɛktɕ͈ɛk/","새 지저귀는 소리","Bird chirping sound","새들이 짹짹 노래한다","The birds sing chirp chirp","tweet tweet / chirp chirp"],
  ["동물 소리","어흥","eoheung","/ʌhɯŋ/","호랑이 울음소리","Tiger roaring sound","호랑이가 어흥 소리친다","The tiger roars rawr","roar"],
  ["동물 소리","히힝","hihing","/hihiŋ/","말 울음소리","Horse neighing sound","말이 히힝 울며 달린다","The horse neighs neigh while running","neigh"],
  ["동물 소리","꽥꽥","quackquack","/kwæk kwæk/","오리 울음소리","Duck quacking sound","오리가 꽥꽥 소리친다","The duck quacks quack quack","quack quack"],
  ["동물 소리","윙윙","wingwing","/wiŋwiŋ/","벌/파리 날개짓 소리","Buzzing sound of insects","벌이 윙윙 날아다닌다","The bee buzzes buzz buzz","buzz buzz"],
  ["동물 소리","갸르릉","gyareureung","/ɡjaɾɯɾɯŋ/","고양이가 기분 좋을 때 내는 소리","Cat purring contentedly","고양이가 갸르릉 기분좋게 운다","The cat purrs contentedly","purr"],
  ["동물 소리","괴발개발","goebalgaebal","/ɡøbalɡɛbal/","글씨를 되는대로 쓴 모양 (고양이 발 개 발)","Messy handwriting like animal paws","글씨를 괴발개발 썼다","Wrote messily like animal paws",""],
  ["동물 소리","기럭기럭","gireokgireok","/ɡiɾʌkɡiɾʌk/","기러기 울음소리","Wild geese honking","기러기가 기럭기럭 날아간다","The geese fly honking","honk"],
  ["동물 소리","끼룩끼룩","kkirukkkiruk","/k͈iɾuk͈kiɾuk/","기러기 울음소리","Goose honking sound","가을 하늘에 기러기가 끼룩끼룩","Geese honk in the autumn sky","honk"],
  ["동물 소리","삐악삐악","ppiakppiak","/p͈iakp͈iak/","병아리 울음소리","Baby chick peeping","병아리가 삐악삐악 어미를 찾는다","The chick peeps searching for mother","peep peep"],
  ["동물 소리","으르렁","eureureong","/ɯɾɯɾʌŋ/","짐승이 위협하는 소리","Beast growling threateningly","사자가 으르렁 위협한다","The lion growls threateningly","growl / grrr"],
  ["동물 소리","으르릉","eureureung","/ɯɾɯɾɯŋ/","천둥/짐승 소리","Thunder or beast roaring","호랑이가 으르릉 소리낸다","The tiger roars loudly","rumble / roar"],
  ["말/대화","꼬치꼬치","kkochikkochi","/k͈otɕʰik͈otɕʰi/","꼬치꼬치 캐묻는 모양 (꼬치가 꾀어진 모습)","Questioning persistently","꼬치꼬치 캐묻는다","Questioning persistently",""],
  ["말/대화","와글와글","wageulwageul","/waɡɯlwaɡɯl/","시끄럽게 떠드는 소리","Chattering noisily","시장이 와글와글","Market is bustling with chatter",""],
  ["말/대화","왁다글닥다글","wakdageul-dakdageul","/wak̚taɡɯɭ tak̚taɡɯɭ/","시끄럽게 떠드는 모양","Very noisy chatter","교실이 왁다글닥다글","Classroom is very noisy",""],
  ["말/대화","왁시글왁시글","wakshigeul-wakshigeul","/wak̚ɕiɡɯɭ wak̚ɕiɡɯɭ/","왁자지껄한 모양","Bustling noisily","식당이 왁시글왁시글","Restaurant is bustling",""],
  ["말/대화","왁자지껄","wakjajikkeol","/wak̚t͡ɕad͡ʑik͈ʌɭ/","떠들썩한 모양","Boisterous or rowdy","잔치가 왁자지껄","Party is boisterous",""],
  ["맛/냄새","고소고소","gosogoso","/ɡosoɡoso/","고소한 냄새가 나는 모양","Nutty or savory aroma","깨를 볶으니 고소고소","Sesame roasts with nutty aroma",""],
  ["맛/냄새","고소하게","gosohage","/ɡosohaɡe/","고소하게","In a nutty or savory way","참기름이 고소하게 향긋하다","Sesame oil smells nutty and fragrant",""],
  ["맛/냄새","구릿구릿","gurit-gurit","/kuɾit̚ kuɾit̚/","구린 냄새가 나는 모양","Stinky or foul smell","쓰레기가 구릿구릿 냄새난다","Garbage smells foul",""],
  ["맛/냄새","구수하게","gusuhage","/ɡusuhaɡe/","구수한 냄새가 나는 모양","In a rich savory way","된장국이 구수하게 끓는다","Bean paste soup boils with savory aroma",""],
  ["맛/냄새","달달하게","daldalhage","/daldalhaɡe/","달달하게","In a sweet way","초콜릿이 달달하게 녹는다","Chocolate melts sweetly",""],
  ["맛/냄새","담백하게","dambaekhage","/dambɛkhaɡe/","담백하게","In a light and mild way","두부요리가 담백하게 맛있다","Tofu dish tastes mild and delicious",""],
  ["맛/냄새","비릿비릿","birit-birit","/piɾit̚ piɾit̚/","비린 냄새가 나는 모양","Fishy smell","생선이 비릿비릿 냄새난다","Fish smells fishy",""],
  ["맛/냄새","상큼상큼","sangkeumsangkeum","/saŋkɯmsaŋkɯm/","상큼한 느낌","Fresh and tangy","레몬이 상큼상큼","Lemon is fresh and tangy",""],
  ["맛/냄새","향긋향긋","hyanggeut-hyanggeut","/çaŋɡɯt̚ çaŋɡɯt̚/","향긋한 냄새","Fragrant smell","꽃이 향긋향긋 향기롭다","Flowers smell fragrant",""],
  ["맛/냄새","향기롭게","hyanggiropge","/hjaŋɡiɾopɡe/","향기롭게","Fragrantly","장미가 향기롭게 핀다","Rose blooms fragrantly",""],
  ["모양/형태","빽빽","ppaekppaek","/p͈ɛkp͈ɛk/","빽빽하게 들어찬 모양","Densely packed","나무가 빽빽하게 심어졌다","Trees planted densely",""],
  ["모양/형태","가닥가닥","gadakgadak","/ɡadakɡadak/","가닥가닥 나뉜 모양 (가닥에서 파생)","In strands","머리카락이 가닥가닥","Hair in strands",""],
  ["모양/형태","가득가득","gadeukgadeuk","/ɡadɯkɡadɯk/","가득 찬 모양","Completely full","사랑이 가득가득","Completely full of love",""],
  ["모양/형태","가리가리","garigari","/ɡaɾiɡaɾi/","가르는 모양","Dividing or separating","가리가리 나누다","Dividing into parts",""],
  ["모양/형태","갈기갈기","galgigalgi","/ɡalɡiɡalɡi/","갈기갈기 찢는 모양","Torn to shreds","종이를 갈기갈기 찢었다","Tore paper to shreds",""],
  ["모양/형태","구깃구깃","gugitgugit","/ɡuɡitɡuɡit/","구겨진 모양","Wrinkled or crumpled","옷이 구깃구깃 구겨졌다","Clothes are wrinkled",""],
  ["모양/형태","구불구불","gubulgubul","/ɡubulɡubul/","굽이져 휘어진 모양","Winding or curvy","뱀이 구불구불 기어간다","Snake slithers in winding path",""],
  ["모양/형태","길쭉길쭉","giljjukgiljjuk","/ɡiltɕ͈ukɡiltɕ͈uk/","길게 늘어난 모양","Long and thin","콩나물이 길쭉길쭉","Bean sprouts are long and thin",""],
  ["모양/형태","다닥다닥/더덕더덕","dadakdadak","/dadakdadak/","다닥다닥 붙은 모양","Stuck closely together","딱지가 다닥다닥 붙었다","Stickers stuck closely together",""],
  ["모양/형태","대롱대롱","daerongdaerong","/dɛɾoŋdɛɾoŋ/","매달린 모양 (대롱이 매달린 모습)","Dangling","열매가 대롱대롱 매달렸다","Fruits hang dangling",""],
  ["모양/형태","더덕더덕/터덕터덕/떠덕떠덕","deodeokdeodeok","/dʌdʌkdʌdʌk/","덕지덕지 붙은 모양","Covered with patches","반창고가 더덕더덕","Bandages stuck all over",""],
  ["모양/형태","덕지덕지","deokjideokji","/dʌktɕidʌktɕi/","덕지덕지 붙은 모양","Thickly coated","때가 덕지덕지","Dirt thickly coated",""],
  ["모양/형태","도돌도돌","dodoldodol","/dodoldodol/","작은 것들이 도드라지게 나온 모양","Bumpy surface","표면이 도돌도돌","Surface is bumpy",""],
  ["모양/형태","동동/둥둥","dongdong","/doŋdoŋ/","물에 떠 있는 모양","Floating","오리가 물에 둥둥 떠있다","Duck floats on water",""],
  ["모양/형태","동실동실","dongsildongsil","/doŋsildoŋsil/","둥실둥실 떠 있는 모양","Floating gently","구름이 동실동실 떠간다","Clouds float gently",""],
  ["모양/형태","두리둥실","duridungsil","/duɾiduŋsil/","둥실둥실한 모양","Floating softly","구름이 두리둥실","Clouds drift softly",""],
  ["모양/형태","두리뭉실","durimungsil","/duɾimuŋsil/","두리뭉실한 모양","Vague or roundish","두리뭉실하게 말한다","Speaking vaguely",""],
  ["모양/형태","둥글둥글","dunggeuldunggeul","/duŋɡɯlduŋɡɯl/","둥근 모양","Round shape","수박이 둥글둥글","Watermelon is round",""],
  ["모양/형태","드문드문","deumundeumun","/dɯmundɯmun/","사이가 뜨문뜨문한 모양","Sparse or scattered","나무가 드문드문 서있다","Trees stand sparsely",""],
  ["모양/형태","득시글득시글","deuksigeuldeuksigeul","/dɯksiɡɯldɯksiɡɯl/","득시글거리는 모양","Swarming","벌레가 득시글득시글","Bugs swarm",""],
  ["모양/형태","듬뿍","deumppuk","/dɯmp͈uk/","가득한 모양","Abundantly","사랑을 듬뿍 담아서","Filled abundantly with love",""],
  ["모양/형태","떡/딱","tteok","/t͈ʌk/","단단히 고정된 모양","Firmly fixed","떡 벌어진 어깨","Broad shoulders firmly set",""],
  ["모양/형태","또랑또랑","ttorangttorang","/t͈oɾaŋt͈oɾaŋ/","맑고 또렷한 모양","Clear and bright","목소리가 또랑또랑","Voice is clear and bright",""],
  ["모양/형태","띄엄띄엄","ttwieomttwieom","/t͈wiʌmt͈wiʌm/","사이를 두고 떨어져 있는 모양","At intervals","띄엄띄엄 서있다","Standing at intervals",""],
  ["모양/형태","말끔","malkkeum","/malk͈ɯm/","깨끗한 모양","Clean and neat","방을 말끔히 청소했다","Cleaned room neat and tidy",""],
  ["모양/형태","멋짐멋짐","meotjim-meotjim","/mʌt̚t͡ɕim mʌt̚t͡ɕim/","멋진 모양","Looking cool or stylish","멋짐멋짐 모델 같다","Looking cool and stylish like a model",""],
  ["모양/형태","멜렁멜렁","melreongmelreong","/melɾʌŋmelɾʌŋ/","멜렁거리는 모양","Swaying loosely","머리가 멜렁멜렁","Hair sways loosely",""],
  ["모양/형태","몽글몽글","monggeulmonggeul","/moŋɡɯlmoŋɡɯl/","몽글몽글 뭉친 모양","Soft and round","구름이 몽글몽글","Clouds are soft and round",""],
  ["모양/형태","몽실몽실","mongsilmongsil","/moŋsilmoŋsil/","포동포동한 모양","Plump and cute","아기가 몽실몽실 귀엽다","Baby is plump and cute",""],
  ["모양/형태","뭉게뭉게","munggemungge","/muŋɡemuŋɡe/","구름이 뭉게뭉게 피어오르는 모양","Billowing clouds","구름이 뭉게뭉게 피어오른다","Clouds billow up",""],
  ["모양/형태","뭉글뭉글","munggeulmunggeul","/muŋɡɯlmuŋɡɯl/","뭉글뭉글 뭉친 모양","Lumpy","반죽이 뭉글뭉글","Dough is lumpy",""],
  ["모양/형태","뭉뚝","mungttuk","/muŋt͈uk/","뭉툭한 모양","Blunt or stubby","연필이 뭉뚝하다","Pencil is blunt",""],
  ["모양/형태","봉긋","bonggeut","/poŋɡɯt̚/","봉긋 솟은 모양","Slightly raised","언덕이 봉긋 솟았다","Hill rises slightly",""],
  ["모양/형태","불룩불룩","bulrukbulruk","/bulɾukbulɾuk/","부풀어 오른 모양","Bulging out","배가 불룩불룩","Belly bulges out",""],
  ["모양/형태","불쑥","bulssuk","/buls͈uk/","갑자기 나타나는 모양","Suddenly appearing","갑자기 불쑥 나타났다","Appeared suddenly",""],
  ["모양/형태","비뚤비뚤","bittulbittul","/bit͈ulbit͈ul/","비뚤어진 모양","Crooked or uneven","글씨가 비뚤비뚤","Writing is crooked",""],
  ["모양/형태","비리비리","biribiri","/biɾibiɾi/","가냘프고 약한 모양","Frail or weak looking","비리비리 마른 체격","Frail and weak physique",""],
  ["모양/형태","비스듬","biseudeum","/bisɯdɯm/","비스듬히 기울어진 모양","Tilted or slanted","비스듬히 기울어졌다","Tilted at an angle",""],
  ["모양/형태","빼딱빼딱","ppaettakppaettak","/p͈ɛt͈akp͈ɛt͈ak/","비뚤어진 모양","Askew or tilted","모자를 빼딱빼딱 썼다","Wore hat askew",""],
  ["모양/형태","빼죽빼죽","ppaejukppaejuk","/p͈ɛtɕukp͈ɛtɕuk/","뾰족하게 내민 모양","Sticking out pointedly","갈대가 빼죽빼죽","Reeds stick out pointedly",""],
  ["모양/형태","뿅","ppyong","/p͈joŋ/","갑자기 사라지는 모양","Disappearing suddenly","마법처럼 뿅 사라졌다","Disappeared suddenly like magic",""],
  ["모양/형태","삐뚤삐뚤","ppittulppittul","/p͈it͈ulp͈it͈ul/","비뚤어진 모양","Crooked","울타리가 삐뚤삐뚤","Fence is crooked",""],
  ["모양/형태","삐죽삐죽","ppijukppijuk","/p͈itɕukp͈itɕuk/","뾰족하게 튀어나온 모양","Pointed or protruding","풀이 삐죽삐죽 자랐다","Grass grew pointed and protruding",""],
  ["모양/형태","살랑살랑","salrangsalrang","/salɾaŋsalɾaŋ/","살랑거리는 모양","Swaying gently","강아지 꼬리가 살랑살랑","Puppy tail wags gently",""],
  ["모양/형태","아기자기","agijagi","/aɡitɕaɡi/","아기자기한 모양","Cute and charming","소품이 아기자기하다","Decorations are cute and charming",""],
  ["모양/형태","알쏭달쏭","alssongdalssong","/als͈oŋdals͈oŋ/","알쏭달쏭한 모양","Puzzling or confusing","수수께끼가 알쏭달쏭","Riddle is puzzling",""],
  ["모양/형태","얼기설기","eolgiseolgi","/ʌlɡisʌlɡi/","성글게 엉킨 모양","Loosely woven","나뭇가지가 얼기설기 엮였다","Branches woven loosely",""],
  ["모양/형태","오글오글","ogeulogeul","/oɡɯloɡɯl/","오글거리는 모양","Crinkled or gathered","종이가 오글오글","Paper is crinkled",""],
  ["모양/형태","오돌토돌","odoltodol","/odoltodol/","오돌도돌 돋은 모양","Bumpy or uneven surface","피부가 오돌토돌","Skin has bumpy surface",""],
  ["모양/형태","우글우글","ugeulugeul","/uɡɯluɡɯl/","우글거리는 모양","Swarming or teeming","구더기가 우글우글","Maggots swarm",""],
  ["모양/형태","이글이글","igeuligeul","/iɡɯliɡɯl/","불이 세게 타오르는 모양","Blazing intensely","불이 이글이글 타오른다","Fire blazes intensely",""],
  ["모양/형태","주렁주렁","jureongjureong","/tɕuɾʌŋtɕuɾʌŋ/","열매 등이 많이 매달린 모양","Hanging in clusters","포도가 주렁주렁 열렸다","Grapes hang in clusters",""],
  ["모양/형태","쭈글쭈글","jjugeuljjugeul","/tɕ͈uɡɯltɕ͈uɡɯl/","쭈글쭈글한 모양","Wrinkled or shriveled","할머니 손이 쭈글쭈글","Grandmother's hands are wrinkled",""],
  ["모양/형태","쭈글쭈글/자글자글","jjugeuljjugeul","/tɕ͈uɡɯltɕ͈uɡɯl/","쭈글쭈글한 모양","Wrinkled up","피부가 쭈글쭈글","Skin is wrinkled",""],
  ["모양/형태","텅텅","teongteong","/tʌŋtʌŋ/","텅 빈 모양","Completely empty","방이 텅텅 비었다","Room is completely empty",""],
  ["모양/형태","헤벌레","hebeolre","/hebʌlɾe/","입이 벌어진 모양","Mouth wide open","입이 헤벌레 벌어졌다","Mouth opened wide",""],
  ["모양/형태","헤벌쭉","hebeoljjuk","/hebʌltɕ͈uk/","입이 크게 벌어진 모양","Gaping wide","입을 헤벌쭉 벌렸다","Opened mouth gaping wide",""],
  ["빛/색깔","감감/캄캄/깜깜","gamgam","/ɡamɡam/","매우 어두운 모양","Pitch dark","밤이 캄캄하다","Night is pitch dark",""],
  ["빛/색깔","거무충충","geomuchungchung","/ɡʌmutɕʰuŋtɕʰuŋ/","거무스름하고 어두운 모양","Dark and gloomy","하늘이 거무충충하다","Sky is dark and gloomy",""],
  ["빛/색깔","거뭇거뭇","geomutgeomut","/ɡʌmutɡʌmut/","검은 빛이 나는 모양","Darkish spots","얼굴에 거뭇거뭇 주근깨가","Dark freckles on face",""],
  ["빛/색깔","깜빡깜빡","kkamppakkkamppak","/k͈amp͈ak͈kamp͈ak/","깜빡거리는 모양","Blinking or flickering","별이 깜빡깜빡 빛난다","Stars twinkle blink blink",""],
  ["빛/색깔","노릇노릇","noreutnoreut","/noɾɯtnoɾɯt/","노란 빛깔로 익은 모양","Golden brown color","빵이 노릇노릇 구워졌다","Bread baked golden brown",""],
  ["빛/색깔","반드르르","bandeureureu","/bandɯɾɯɾɯ/","매끄럽고 빛나는 모양","Sleek and shiny","머리카락이 반드르르","Hair is sleek and shiny",""],
  ["빛/색깔","반득반득","bandeukbandeuk","/bandɯkbandɯk/","빛나는 모양","Gleaming brightly","눈이 반득반득 빛난다","Eyes gleam brightly",""],
  ["빛/색깔","반들반들","bandeulbandeul","/bandɯlbandɯl/","매끄럽게 빛나는 모양","Shiny and smooth","구두를 반들반들 닦았다","Polished shoes shiny",""],
  ["빛/색깔","반질반질","banjilbanjil","/bantɕilbantɕil/","반들반들한 모양","Glossy and smooth","마루가 반질반질 윤이 난다","Floor shines glossy",""],
  ["빛/색깔","반짝","banjjak","/bantɕ͈ak/","빛나는 모양","Sparkling or twinkling","반짝반짝 작은 별 아름답게 빛나네","Twinkle twinkle little star shining beautifully","twinkle / sparkle"],
  ["빛/색깔","번뜩","beontteuk","/bʌnt͈ɯk/","번쩍 빛나는 모양","Flashing brilliantly","아이디어가 번뜩 떠올랐다","Idea flashed brilliantly",""],
  ["빛/색깔","번뜻번뜻","beonteut-beonteut","/pʌntɯt̚ pʌntɯt̚/","번쩍번쩍 빛나는 모양","Flashing repeatedly","번뜻번뜻 빛이 난다","Light flashes repeatedly",""],
  ["빛/색깔","번쩍","beonjjeok","/bʌntɕ͈ʌk/","번쩍 빛나는 모양","Lightning flash","번개가 번쩍 친다","Lightning flashes","flash"],
  ["빛/색깔","불그레","bulgeure","/bulɡɯɾe/","불그스름한 모양","Reddish or blushing","볼이 불그레 물들었다","Cheeks blush reddish",""],
  ["빛/색깔","어둑어둑","eodukeoduk","/ʌdukʌduk/","어두워지는 모양","Getting dark or dim","해가 져서 어둑어둑","Getting dark at sunset",""],
  ["빛/색깔","울긋불긋","ulgeut-bulgeut","/uɭɡɯt̚ puɭɡɯt̚/","여러 색깔이 어우러진 모양","Various bright colors","단풍이 울긋불긋 물들었다","Autumn leaves turn various bright colors",""],
  ["빛/색깔","윤기윤기","yungiyungi","/juŋijuŋi/","윤기 나는 모양","Glossy or lustrous","머리카락이 윤기윤기","Hair is glossy and lustrous",""],
  ["빛/색깔","쨍쨍","jjaengjjaeng","/tɕ͈ɛŋtɕ͈ɛŋ/","햇볕이 강하게 내리쬐는 모양","Bright sunshine","햇볕은 쨍쨍 모래알은 반짝","Sun shines bright and sand grains sparkle",""],
  ["빛/색깔","쨍쨍하게","jjaengjjaenghage","/tɕ͈ɛŋtɕ͈ɛŋhaɡe/","쨍쨍하게 빛나는 모양","Light or color expression","햇볕이 쨍쨍하게 내리쬔다","Sun shines blazingly bright",""],
  ["빛/색깔","초롱초롱","chorongchorong","/tɕʰoɾoŋtɕʰoɾoŋ/","맑고 빛나는 모양 (초롱불과 관련)","Bright and clear eyes","눈이 초롱초롱 빛난다","Eyes shine bright and clear",""],
  ["빛/색깔","푸릇푸릇","pureutpureut","/puɾɯtpuɾɯt/","푸른 빛깔의 모양","Fresh green color","새싹이 푸릇푸릇 돋아난다","Sprouts grow fresh green",""],
  ["사람 소리","하하/호호/히히","haha","/haha/","웃음소리","Various laughter sounds","하하호호 웃음꽃이 피었네","Laughter blooms haha hoho","haha / hoho / hehe"],
  ["사람 소리","킥킥","kikkik","/kik͈ik/","킥킥거리는 웃음","Giggling quietly","친구들이 킥킥거리며 웃는다","Friends giggle hehe","giggle"],
  ["사람 소리","깔깔","kkalkkal","/k͈alk͈al/","깔깔 웃는 소리","Laughing heartily","아이들이 깔깔 웃는다","Children laugh heartily hahaha","hahaha"],
  ["사람 소리","껄껄","kkeolkkeol","/k͈ʌlk͈ʌl/","껄껄 웃는 소리","Guffawing loudly","할아버지가 껄껄 웃으신다","Grandfather guffaws loudly","guffaw"],
  ["사람 소리","에취","echwi","/etɕʰwi/","재채기 소리","Sneezing sound","감기 걸려서 에취 재채기","Sneezing achoo with a cold","achoo"],
  ["사람 소리","딸꾹","ttalkkuk","/t͈alk͈uk/","딸꾹질 소리","Hiccup sound","딸꾹딸꾹 딸꾹질이 멈추질 않네","Hiccups won't stop","hiccup"],
  ["사람 소리","콜록콜록","kolrokkolrok","/kolɾok͈olɾok/","기침 소리","Coughing repeatedly","감기 걸려 콜록콜록 기침한다","Coughing repeatedly with a cold","cough cough"],
  ["사람 소리","켁켁","kekkek","/kek͈ek/","심한 기침 소리","Severe coughing or choking","목이 막혀 켁켁거린다","Choking and coughing","hack hack"],
  ["사람 소리","훌쩍훌쩍","huljjeokhuljjeok","/hultɕ͈ʌkhultɕ͈ʌk/","코를 훌쩍이는 소리","Sniffling repeatedly","코를 훌쩍훌쩍 풀었다","Blew nose sniffling","sniffle sniffle"],
  ["사람 소리","아야/앗","aya","/aja/","아플 때 내는 소리","Exclamation of pain or surprise","앗, 뜨거워! 아야!","Ouch! It's hot! Ow!","ouch / ow"],
  ["사람 소리","엉엉","eongeong","/ʌŋʌŋ/","크게 우는 소리","Crying loudly","아기가 엉엉 운다","The baby cries loudly boo-hoo","wah wah / boo hoo"],
  ["사람 소리","훌쩍","huljjeok","/hultɕ͈ʌk/","울면서 코를 훌쩍이는 소리","Sobbing with sniffling","슬퍼서 훌쩍 울었다","Cried sadly with sniffles","sniff"],
  ["사람 소리","펑펑","peongpeong","/pʌŋpʌŋ/","통곡하는 소리","Wailing heavily","서러워서 펑펑 울었다","Wailed heavily in sorrow","sob sob"],
  ["사람 소리","찡찡","jjingjjing","/tɕ͈iŋtɕ͈iŋ/","아이가 칭얼거리며 우는 소리","Child whining or fussing","아이가 찡찡 보챈다","The child whines and fusses","whine"],
  ["사람 소리","꺅","kkya","/k͈ja/","비명 소리","Screaming in surprise","꺅 소리치며 놀랐다","Screamed in surprise eek","scream / eek"],
  ["사람 소리","방그레","banggeure","/baŋɡɯɾe/","빙그레 웃는 모양","Smiling gently","아기가 방그레 웃는다","Baby smiles gently",""],
  ["사람 소리","방긋방긋","banggeut-banggeut","/paŋɡɯt̚ paŋɡɯt̚/","방긋 웃는 모양","Smiling brightly","꽃이 방긋방긋 웃는다","Flowers smile brightly",""],
  ["사람 소리","방실방실","bangsilbangsil","/baŋsilbaŋsil/","방긋방긋 웃는 모양","Beaming with joy","해바라기가 방실방실 웃는다","Sunflower beams joyfully",""],
  ["사람 소리","방실방실/벙실벙실","bangsilbangsil","/baŋsilbaŋsil/","방긋방긋 웃는 모양","Smiling broadly","아기가 방실방실 웃는다","Baby smiles beamingly",""],
  ["사람 소리","싱그레","singgeure","/siŋɡɯɾe/","싱그럽게 웃는 모양","Smiling freshly or radiantly","봄이 되니 얼굴에 싱그레 웃음이","Spring brings a fresh smile to face",""],
  ["사람 소리","엄지척","eomjicheok","/ʌmtɕitɕʰʌk/","엄지를 척 치켜세우는 모양","Giving thumbs up","잘했어! 엄지척!","Well done! Thumbs up!",""],
  ["사람 소리","옹알옹알/웅얼웅얼","ongalongal","/oŋaloŋal/","옹알거리는 소리","Baby babbling","아기가 옹알옹알 말을 배운다","Baby learns to talk babbling",""],
  ["사람 소리","울고불고","ulgobulgo","/ulɡobulɡo/","울고불고하는 모양 (울고 블고)","Crying and wailing","아이가 울고불고 떼를 쓴다","Child throws tantrum crying and wailing",""],
  ["사람 소리","울먹울먹","ulmeokulmeok","/ulmʌkulmʌk/","울먹거리는 모양","On the verge of tears","울먹울먹 눈물을 참는다","Holding back tears trembling",""],
  ["사람 소리","쫑알쫑알/중얼중얼","jjongaljjongal","/tɕ͈oŋaltɕ͈oŋal/","중얼거리는 소리","Muttering to oneself","혼자서 중얼중얼 말한다","Mutters to oneself",""],
  ["사람 소리","칭얼칭얼","chingeolchingeol","/tɕʰiŋʌltɕʰiŋʌl/","칭얼거리는 소리","Whining or complaining","아기가 칭얼칭얼 보챈다","Baby whines and fusses",""],
  ["사람 소리","헤실헤실","hesilhesil","/hesilhesil/","실없이 웃는 모양","Grinning foolishly","아이가 헤실헤실 웃는다","Child grins foolishly",""],
  ["사람 소리","헤죽헤죽","hejukhejuk","/hetɕukhetɕuk/","실없이 웃는 모양","Smirking sillily","실없이 헤죽헤죽 웃지마","Don't smirk sillily",""],
  ["사람 소리","헤헤","hehe","/hehe/","실없이 웃는 소리","Laughing foolishly","헤헤 웃으며 장난친다","Laughs hehe while playing pranks","hehe"],
  ["사람 소리","흥얼흥얼","heungeolheungeol","/hɯŋʌlhɯŋʌl/","흥얼거리는 소리","Humming a tune","콧노래를 흥얼흥얼 부른다","Hums a tune",""],
  ["상태/정도","칙칙","chikchik","/tɕʰiktɕʰik/","어둡고 칙칙한 느낌","Dull and gloomy","날씨가 칙칙하다","Weather is dull and gloomy",""],
  ["상태/정도","가뿐","kappoon","/ka̠p͈un/","가볍고 경쾌한 느낌","Light and nimble","몸이 가뿐하다","Body feels light and nimble",""],
  ["상태/정도","따끈따끈","ttakkeunttakkeun","/t͈ak͈ɯnt͈ak͈ɯn/","따끈한 느낌","Warm or hot","군고구마가 따끈따끈","Roasted sweet potato is warm",""],
  ["상태/정도","뜨끈뜨끈","tteukkeuntteukkeun","/t͈ɯk͈ɯnt͈ɯk͈ɯn/","뜨거운 느낌","Very warm","찜질방이 뜨끈뜨끈","Sauna is very warm",""],
  ["상태/정도","빠릿빠릿","pparit-pparit","/p͈aɾit̚ p͈aɾit̚/","빠르고 민첩한 모양","Quick and agile","일처리가 빠릿빠릿","Work is done quickly and efficiently",""],
  ["상태/정도","사뿐하게","sappunhage","/sap͈unhaɡe/","가볍게","Lightly and gently","발을 사뿐하게 내딛는다","Stepping lightly",""],
  ["상태/정도","사알사알","saalsaal","/saalsaal/","살살","Very gently","사알사알 다루다","Handle very gently",""],
  ["상태/정도","사알짝","saaljjak","/saaltɕ͈ak/","살짝","Very slightly","사알짝 건드렸다","Touched very slightly",""],
  ["상태/정도","산뜻하게","santteuthage","/sant͈ɯtʰaɡe/","산뜻하게","State or degree","아침공기가 산뜻하게 상쾌하다","Morning air is refreshingly clean",""],
  ["상태/정도","살며시","salmyeosi","/salmjʌsi/","살며시 조용히","Quietly or gently","살며시 문을 열었다","Opened door quietly",""],
  ["상태/정도","살살","salsal","/salsal/","살살 다루는 모양","Gently or carefully","살살 다뤄야 한다","Must handle gently",""],
  ["상태/정도","살짝/슬쩍","saljjak","/saltɕ͈ak/","살짝 하는 모양","Slightly or stealthily","살짝 맛보았다","Tasted slightly",""],
  ["상태/정도","살포시","salposi","/salposi/","살며시 가볍게","Softly or lightly","살포시 입맞춤했다","Kissed softly",""],
  ["상태/정도","생생","saengsaeng","/sɛŋsɛŋ/","싱싱한 모양","Vivid or fresh","기억이 생생하다","Memory is vivid",""],
  ["상태/정도","싱싱","singsing","/siŋsiŋ/","생생하고 싱싱한 모양","Fresh and lively","채소가 싱싱하다","Vegetables are fresh",""],
  ["상태/정도","시끌시끌","sikkeulsikkeul","/sik͈ɯlsik͈ɯl/","시끄러운 모양","Noisy or bustling","교실이 시끌시끌","Classroom is noisy",""],
  ["상태/정도","쑥쑥","ssukssuk","/s͈uks͈uk/","쑥쑥 자라는 모양","Growing rapidly","키가 쑥쑥 자란다","Growing rapidly",""],
  ["상태/정도","알차게","alchage","/altɕʰaɡe/","알차게","State or degree","내용을 알차게 준비했다","Prepared content substantially",""],
  ["상태/정도","어둑충충","eodukchungchung","/ʌduktɕʰuŋtɕʰuŋ/","어둑하고 침침한 모양","Dark and gloomy","지하실이 어둑충충","Basement is dark and gloomy",""],
  ["상태/정도","어정쩡","eojeongjjeong","/ʌd͡ʑʌŋt͡ɕ͈ʌŋ/","어중간한 모양","Awkwardly in between","어정쩡 서있다","Standing awkwardly",""],
  ["상태/정도","우중충","ujungchung","/utɕuŋtɕʰuŋ/","어둡고 칙칙한 모양","Dark and dreary","날씨가 우중충하다","Weather is dark and dreary",""],
  ["상태/정도","점점","jeomjeom","/tɕʌmtɕʌm/","점점 변하는 모양","Gradually","점점 좋아진다","Getting better gradually",""],
  ["상태/정도","조금조금","jogeumjogeum","/tɕoɡɯmtɕoɡɯm/","조금씩 조금씩","Little by little","조금조금 먹는다","Eating little by little",""],
  ["상태/정도","조심조심","josimjosim","/tɕosimtɕosim/","조심하는 모양","Carefully","조심조심 걷는다","Walking carefully",""],
  ["상태/정도","조용조용","joyongjoyong","/tɕojoŋtɕojoŋ/","조용한 모양","Quietly","조용조용히 지낸다","Living quietly",""],
  ["상태/정도","질금/칠큼/찔끔","jilgeum","/tɕilɡɯm/","조금씩 흘리는 모양","Bit by bit","눈물이 찔끔 났다","Tears came bit by bit",""],
  ["상태/정도","파삭","pasak","/pasak/","파삭한 느낌","Crispy or flaky","과자가 파삭하다","Cookie is crispy and flaky",""],
  ["상태/정도","푸짐푸짐","pujimpujim","/putɕimputɕim/","푸짐한 모양","Abundant or plentiful","상이 푸짐푸짐하다","Table is abundantly full",""],
  ["상태/정도","허허실실","heoheosilsil","/hʌhʌsilsil/","허실을 알 수 없는 모양","Mixing truth and feint","허허실실 싸우다","Fighting mixing truth and feint",""],
  ["상태/정도","후끈","hukkeun","/huk͈ɯn/","후끈한 느낌","Flushed or heated","얼굴이 후끈 달아올랐다","Face flushed hot",""],
  ["소리","째깍째깍","jjaekkakjjaekkak","/tɕ͈ɛk͈aktɕ͈ɛk͈ak/","시계 소리","Clock ticking","시계가 째깍째깍","Clock ticks tick tock","tick tock"],
  ["소리","삐삐/띠띠","ppippi","/p͈ip͈i/","전자음","Beeping sound","기계가 삐삐 소리낸다","Machine beeps","beep beep"],
  ["소리","쿵쿵","kungkung","/kuŋkuŋ/","발소리나 두드리는 소리","Thumping sound","심장이 쿵쿵 뛴다","Heart thumps thud thud","thud thud / boom boom"],
  ["소리","휙휙","hwikhwik","/hwikhwik/","바람을 가르는 소리","Whooshing sound","바람이 휙휙 분다","Wind blows whoosh whoosh","whoosh whoosh"],
  ["소리","쪽","jjok","/tɕ͈ok/","뽀뽀하는 소리","Kissing sound","볼에 쪽 뽀뽀했다","Gave a kiss on the cheek mwah",""],
  ["소리","궁/쿵/꿍","gung","/ɡuŋ/","무거운 물체가 부딪히는 소리","Heavy impact sound","문을 쿵쿵 두드린다","Knocking on door thump thump",""],
  ["소리","깨드득","kkaedeudeuk","/k͈ɛdɯdɯk/","깨물어 부수는 소리","Crunching sound","사탕을 깨드득 깨물었다","Crunched candy",""],
  ["소리","꺽꺽/컥컥","kkeok-kkeok / keok-keok","/k͈ʌk̚k͈ʌk̚ / kʌk̚kʌk̚/","목이 막히는 소리","Choking sound","목이 메어 컥컥거린다","Choking with throat blocked",""],
  ["소리","꿍얼꿍얼","kkungeolkkungeol","/k͈uŋʌlk͈uŋʌl/","꿍얼거리는 소리","Grumbling","뭔가 꿍얼꿍얼 말한다","Grumbling something unintelligibly",""],
  ["소리","끄르륵","kkeureureuk","/k͈ɯɾɯɾɯk/","배에서 나는 소리","Stomach growling","배에서 끄르륵 소리난다","Stomach growls rumble",""],
  ["소리","끼깅끼깅","kkiging-kkiging","/k͈iɡiŋ k͈iɡiŋ/","끼깅거리는 소리","Sawing sound","톱이 끼깅끼깅 소리낸다","Saw makes grinding sound",""],
  ["소리","끼익","kkiik","/k͈iik/","삐걱거리는 소리","Creaking or squeaking","문이 끼익 열린다","Door opens with squeak","creak / squeak"],
  ["소리","나직나직","najiknajik","/natɕiknatɕik/","낮은 목소리나 소리로 조용히 하는 모양","Speaking softly","나직나직 속삭인다","Whispering softly",""],
  ["소리","닥","dak","/dak/","닥 붙는 소리","Slamming shut","문이 닥 닫혔다","Door slammed shut",""],
  ["소리","달각/탈칵/딸깍","dalgak","/dalɡak/","딸깍거리는 소리","Clicking","스위치가 딸깍","Switch clicks",""],
  ["소리","달그락","dalgeurak","/dalɡɯɾak/","달그락 소리","Rattling dishes","그릇이 달그락거린다","Bowls rattle",""],
  ["소리","당당/탕탕/땅땅","dangdang","/daŋdaŋ/","두드리는 소리","Banging or hammering","망치로 땅땅 두드린다","Hammering bang bang",""],
  ["소리","덜걱/털컥/떨꺽","deolgeok / teolkeok / tteolgeok","/tʌɭɡʌk̚ / tʌɭkʌk̚ / t͈ʌɭk͈ʌk̚/","덜컥거리는 소리","Clattering open","문이 털컥 열렸다","Door clattered open suddenly",""],
  ["소리","덜그덕/덜그럭","deolgeudeok","/dʌlɡɯdʌk/","부딪히는 소리","Clanking sound","그릇이 덜그럭 소리난다","Dishes clank and rattle",""],
  ["소리","덜컥덜컥","deolkeokdeolkeok","/dʌlkʌkdʌlkʌk/","덜컥거리는 소리","Rattling","창문이 덜컥덜컥","Window rattles noisily",""],
  ["소리","두둑","duduk","/duduk/","부러지는 소리","Cracking sound","뼈가 두둑 소리났다","Bone cracked",""],
  ["소리","두런두런","dureondureon","/duɾʌnduɾʌn/","여럿이 낮은 목소리로 정답게 이야기하는 모양","Chatting quietly","사람들이 두런두런 이야기한다","People chat quietly among themselves",""],
  ["소리","둑","duk","/duk/","둑 소리","Thudding","공이 둑 하고 맞았다","Ball hit with thud",""],
  ["소리","드르렁","deureureong","/dɯɾɯɾʌŋ/","코 고는 소리","Snoring","드르렁 코를 곤다","Snoring loudly",""],
  ["소리","드르르륵","deureureureuk","/dɯɾɯɾɯɾɯk/","드르르륵 소리","Rolling sound","문이 드르르륵 열린다","Door rolls open with sound",""],
  ["소리","드륵","deureuk","/dɯɾɯk/","드륵 소리","Unlocking sound","자물쇠가 드륵 열린다","Lock clicks open",""],
  ["소리","따르릉","ttareureung","/t͈aɾɯɾɯŋ/","전화벨 소리","Ringing bell","전화벨이 따르릉 울린다","Phone rings ring ring","ring ring"],
  ["소리","딱","ttak","/t͈ak/","딱 붙는 소리/모양","Clicking or snapping","딱 소리가 났다","Made a clicking sound",""],
  ["소리","딸랑딸랑","ttalrangttalrang","/t͈alɾaŋt͈alɾaŋ/","방울 소리","Bell jingling","방울이 딸랑딸랑","Bell jingles ring ring","jingle jingle"],
  ["소리","뚝","ttuk","/t͈uk/","뚝 떨어지는 소리/모양","Snapping sound","나뭇가지가 뚝 부러졌다","Branch snapped","snap / crack"],
  ["소리","뚱땅뚱땅","ttungttangttungttang","/t͈uŋt͈aŋt͈uŋt͈aŋ/","뚱땅거리는 소리","Construction noise","공사장에서 뚱땅뚱땅","Construction noise banging",""],
  ["소리","바글바글/부글부글","bageulbageul","/baɡɯlbaɡɯl/","끓는 모양","Boiling vigorously","국이 부글부글 끓는다","Soup boils vigorously",""],
  ["소리","바드득","badeudeuk","/badɯdɯk/","이를 가는 소리","Grinding sound","이를 바드득 갈다","Grinding teeth",""],
  ["소리","바스락","baseurak","/basɯɾak/","바스락거리는 소리","Rustling sound","비닐봉지가 바스락거린다","Plastic bag rustles",""],
  ["소리","바스락/부스럭","baseurak","/basɯɾak/","바스락거리는 소리","Crinkling or rustling","낙엽이 부스럭거린다","Fallen leaves crinkle",""],
  ["소리","벙/펑/뻥","beong","/bʌŋ/","터지는 소리","Popping or exploding","풍선이 펑 터졌다","Balloon popped bang","bang / pop / boom"],
  ["소리","보글보글","bogeulbogeul","/boɡɯlboɡɯl/","끓는 소리","Simmering or bubbling","된장찌개가 보글보글 끓는다","Bean paste stew simmers bubble bubble","bubble bubble / simmer"],
  ["소리","보글보글/포글포글/뽀글뽀글","bogeulbogeul","/boɡɯlboɡɯl/","끓는 소리","Bubbling","라면이 뽀글뽀글 끓는다","Ramen boils with bubbles",""],
  ["소리","보로록","bororok","/boɾoɾok/","보로록 소리","Gurgling stomach","배에서 보로록 소리","Stomach gurgling sound",""],
  ["소리","부드득","budeudeuk","/budɯdɯk/","부드득 소리","Grinding teeth","이를 부드득 갈았다","Grinding teeth",""],
  ["소리","부르릉","bureureung","/buɾɯɾɯŋ/","엔진 소리","Engine revving","자동차가 부르릉 출발한다","Car starts vroom","vroom"],
  ["소리","부웅","buung","/buuŋ/","부웅 소리","Zooming past","비행기가 부웅 지나간다","Airplane zooms past",""],
  ["소리","빵빵","ppangppang","/p͈aŋp͈aŋ/","빵빵 소리/부푼 모양","Honking horn","자동차가 빵빵 경적을 울린다","Car honks horn beep beep","honk honk / beep beep"],
  ["소리","뽀각","ppogak","/p͈oɡak/","뽀각 소리","Footstep sound","발자국이 뽀각뽀각","Footsteps make clicking sound",""],
  ["소리","뽀글뽀글","ppogeulppogeul","/p͈oɡɯlp͈oɡɯl/","끓는 소리","Bubbling up","거품이 뽀글뽀글","Bubbles rise up",""],
  ["소리","뽀드득","ppodeudeuk","/p͈odɯdɯk/","뽀드득 소리","Squeaky clean sound","이가 뽀드득 소리난다","Teeth make squeaky sound",""],
  ["소리","뿅뿅","ppyongppyong","/p͈joŋp͈joŋ/","뿅뿅 소리","Popping sounds","뿅뿅 소리내며 사라진다","Disappears with popping sound",""],
  ["소리","삐","ppi","/p͈i/","높고 가는 소리","High-pitched sound","호루라기가 삐 소리낸다","Whistle blows with high pitch",""],
  ["소리","삐그덕","ppigeudeok","/p͈iɡɯdʌk/","삐걱거리는 소리","Creaking sound","나무 바닥이 삐그덕","Wooden floor creaks","creak"],
  ["소리","삐그덕/삐그럭","ppigeudeok","/p͈iɡɯdʌk/","삐걱거리는 소리","Squeaking","의자가 삐그덕거린다","Chair creaks",""],
  ["소리","삑","ppik","/p͈ik/","삐 소리","Beeping","경적이 삑 울린다","Horn beeps",""],
  ["소리","삘릴리","ppilrilri","/p͈ilɾilɾi/","피리 소리","Flute sound","피리가 삘릴리 소리낸다","Flute sounds melodiously",""],
  ["소리","사각사각","sagaksagak","/saɡaksaɡak/","사각거리는 소리","Scratching or writing","연필이 사각사각","Pencil makes scratching sound",""],
  ["소리","서걱서걱","seogeok-seogeok","/sʌɡʌk̚ sʌɡʌk̚/","서걱거리는 소리","Rustling leaves","낙엽을 밟으며 서걱서걱","Stepping on fallen leaves with rustling",""],
  ["소리","송골송골","songgolsonggol","/soŋɡolsoŋɡol/","땀방울이 맺힌 모양","Beads of sweat forming","이마에 땀이 송골송골","Sweat beads form on forehead",""],
  ["소리","스르륵","seureureuk","/sɯɾɯɾɯk/","부드럽게 스치는 소리","Sliding smoothly","창문이 스르륵 열린다","Window slides open smoothly",""],
  ["소리","쏴아","sswaa","/s͈waː/","물이 쏟아지는 소리","Rushing water","폭포가 쏴아 쏟아진다","Waterfall pours with rushing sound",""],
  ["소리","쓱싹쓱싹","sseukssaksseukssak","/s͈ɯks͈aks͈ɯks͈ak/","쓱싹거리는 모양","Sound effect","칠판을 쓱싹쓱싹 닦는다","Wiping blackboard with sweeping motion",""],
  ["소리","아드득/와드득","adeudeuk","/adɯdɯk/","세게 깨무는 소리","Clenching sound","이를 와드득 깨물었다","Clenched teeth hard",""],
  ["소리","아삭","asak","/asak/","아삭거리는 소리","Crunching sound","사과를 아삭 깨문다","Biting apple with crunch","crunch"],
  ["소리","아삭아삭","asakasak","/asakasak/","아삭거리는 소리","Crispy crunching","오이를 아삭아삭 씹는다","Chewing cucumber crunchily","crunch crunch"],
  ["소리","와르르","wareureu","/waɾɯɾɯ/","무너지는 소리","Collapsing or crumbling","블록이 와르르 무너졌다","Blocks collapsed with crash","crash"],
  ["소리","와르르르","wareureureu","/waɾɯɾɯɾɯ/","무너지는 소리","Crashing down","건물이 와르르르 무너진다","Building crumbles down",""],
  ["소리","와삭","wasak","/wasak/","와삭 소리","Breaking sound","비스킷을 와삭 깨문다","Biting biscuit with crack",""],
  ["소리","우당탕우당탕","udangtangudangtang","/udaŋtaŋudaŋtaŋ/","시끄럽게 부딪히는 소리","Loud crashing","아이들이 우당탕우당탕 뛰어다닌다","Children run around crash bang","crash bang"],
  ["소리","우드득","udeudeuk","/udɯdɯk/","부러지는 소리","Breaking sound","나무가 우드득 부러진다","Tree breaks with crack",""],
  ["소리","작작/착착/짝짝","jakjak","/tɕaktɕak/","착착 맞는 모양/박수 소리","Clapping or fitting","일이 착착 진행된다","Work proceeds smoothly step by step",""],
  ["소리","졸졸","joljol","/tɕoltɕol/","물이 흐르는 소리","Trickling water","시냇물이 졸졸 흐른다","Stream flows with babbling sound","babble / gurgle"],
  ["소리","좌르륵/주르륵","jwareureuk","/tɕwaɾɯɾɯk/","무언가 쏟아지는 소리","Flowing or streaming","눈물이 주르륵 흐른다","Tears stream down",""],
  ["소리","주룩주룩","jurukjuruk","/tɕuɾuktɕuɾuk/","비가 내리는 소리 (줄의 모양과 관련)","Rain falling","비가 주룩주룩 내린다","Rain falls steadily",""],
  ["소리","줄줄","juljul","/tɕultɕul/","줄줄 흐르는 모양 (줄의 모양과 관련)","Streaming down","땀이 줄줄 흐른다","Sweat streams down",""],
  ["소리","주르륵","jureureuk","/tɕuɾɯɾɯk/","주르륵 흐르는 소리","Flowing down","눈물이 주르륵","Tears flow down",""],
  ["소리","지글지글","jigeuljigeul","/tɕiɡɯltɕiɡɯl/","지글거리는 소리","Sizzling sound","고기가 지글지글 익는다","Meat sizzles","sizzle"],
  ["소리","지글탁","jigeultak","/tɕiɡɯltak/","지글탁 소리","Sizzling pop","프라이팬에서 지글탁","Frying pan sizzles",""],
  ["소리","짤그닥/짤그락","jjalgeudak","/tɕ͈alɡɯdak/","금속이 부딪히는 소리","Jingling metal","열쇠가 짤그락거린다","Keys jingle and clank",""],
  ["소리","쨔악","jjaak","/t͡ɕ͈aːk̚/","쨔악 소리","Tearing sound","천을 쨜악 찢었다","Tore cloth with ripping sound",""],
  ["소리","쩌억","jjeoeok","/tɕ͈ʌʌk/","쩌억 소리","Cutting sound","무를 쩌억 자른다","Cutting radish with slicing sound",""],
  ["소리","쩝쩝","jjeopjjeop","/tɕ͈ʌptɕ͈ʌp/","입맛 다시는 소리","Smacking lips","입맛을 쩝쩝 다신다","Smacking lips",""],
  ["소리","쪼로록","jjororok","/tɕ͈oɾoɾok/","쪼로록 소리","Trickling","물이 쪼로록 흐른다","Water trickles",""],
  ["소리","착","chak","/tɕʰak/","달라붙는 소리/모양","Sticking sound","반창고가 착 붙는다","Bandage sticks on firmly",""],
  ["소리","찰랑","chalrang","/tɕʰalɾaŋ/","찰랑거리는 소리","Splashing lightly","물이 찰랑찰랑","Water splashes gently",""],
  ["소리","찰싹","chalssak","/tɕʰals͈ak/","세게 때리는 소리","Slapping sound","파도가 찰싹 부딪힌다","Wave crashes slap","slap / splash"],
  ["소리","찰칵","chalkak","/tɕʰalkak/","찰칵 소리","Camera shutter","카메라가 찰칵","Camera shutter clicks","click / snap"],
  ["소리","챡","chaek","/t͡ɕʰa̠k̚/","챡 소리","Clicking sound","스위치를 챡 켰다","Turned on switch with click",""],
  ["소리","철벙철벙","cheolbeongcheolbeong","/tɕʰʌlbʌŋtɕʰʌlbʌŋ/","물을 튀기는 소리","Splashing around","아이들이 물속에서 철벙철벙","Kids splash in water","splash splash"],
  ["소리","철썩","cheolsseok","/tɕʰʌls͈ʌk/","철썩 소리","Wave crashing","파도가 철썩 부딪힌다","Wave crashes against",""],
  ["소리","철컥","cheolkeok","/tɕʰʌlkʌk/","철컥 잠기는 소리","Clicking shut","문이 철컥 잠겼다","Door locked with click","click / clank"],
  ["소리","철퍽철퍽","cheolpeokcheolpeok","/tɕʰʌlpʌktɕʰʌlpʌk/","철퍽거리는 소리","Slapping water","빗물이 철퍽철퍽","Rain slaps down",""],
  ["소리","치카치카","chikachika","/tɕʰikatɕʰika/","이를 닦는 소리 (齒와 관련)","Brushing teeth","이를 치카치카 닦는다","Brushing teeth back and forth",""],
  ["소리","캘록캘록","kaelrokkaelrok","/kɛlɾok͈ɛlɾok/","캘록거리는 소리 (모음 ㅐ 사용 신조어)","Coughing lightly","기침을 캘록캘록","Coughing lightly",""],
  ["소리","콸콸","kwal-kwal","/kʰwal kʰwal/","콸콸 쏟아지는 소리","Gushing water","물이 콸콸 쏟아진다","Water gushes out",""],
  ["소리","쿵쾅쿵쾅","kungkwangkungkwang","/kuŋkwaŋkuŋkwaŋ/","쿵쾅거리는 소리","Heavy thumping","심장이 쿵쾅쿵쾅 뛴다","Heart thumps heavily",""],
  ["소리","타닥타닥","tadaktadak","/tadaktadak/","타닥거리는 소리","Typing sound","키보드를 타닥타닥","Typing on keyboard tap tap",""],
  ["소리","톡","tok","/tok/","톡 치는 소리","Tapping sound","어깨를 톡 치다","Tapping shoulder lightly",""],
  ["소리","톡톡","toktok","/toktok/","톡톡 두드리는 소리","Knocking or tapping","문을 톡톡 두드린다","Tapping on door tap tap","tap tap"],
  ["소리","투닥투닥","tudaktudak","/tudaktudak/","투닥거리는 소리","Bickering sound","부부가 투닥투닥 싸운다","Couple bickers",""],
  ["소리","투둑","tuduk","/tuduk/","투둑 소리","Dropping sound","물방울이 투둑 떨어진다","Water drop falls with plop",""],
  ["소리","투룩","turuk","/tuɾuk/","투룩 소리","Popping open","뚜껑이 투룩 열린다","Lid pops open",""],
  ["소리","퍼억","peoeok","/pʌʌk/","퍼억 소리","Slapping sound","뺨을 퍼억 맞았다","Got slapped on cheek hard",""],
  ["소리","퐁당","pongdang","/poŋdaŋ/","퐁당 빠지는 소리","Splashing into water","돌멩이가 물에 퐁당","Stone splashed into water plop","splash / plop"],
  ["소리","화르륵/휘리릭/후루룩","hwareureuk","/hwaɾɯɾɯk/","바람이 스치는 소리","Fluttering quickly","새가 휘리릭 날아갔다","Bird flew away swiftly",""],
  ["소리","확/휙/훅","hwak","/hwak/","바람이 스치는 소리","Swooshing wind","바람이 휙 불었다","Wind blew with whoosh","whoosh / swish"],
  ["소리","후루루","hururu","/huɾuɾu/","후루루 소리","Sipping liquid","차를 후루루 마신다","Sipping tea with sound",""],
  ["소리","후루룩","hururuk","/huɾuɾuk/","국물을 먹는 소리","Slurping noodles","국수를 후루룩 먹는다","Slurping noodles",""],
  ["시선/눈","빤히/뻔히","ppanhi","/p͈anhi/","뚫어지게 보는 모양","Staring intently","뻔히 쳐다본다","Staring intently",""],
  ["시선/눈","흘깃","heulgit","/hɯlɡit/","슬쩍 흘겨보는 모양","Glancing sideways","흘깃 쳐다보았다","Glanced sideways",""],
  ["시선/눈","희번득","huibeondeuk","/huibʌndɯk/","눈을 희번득거리는 모양","Eyes flashing","눈을 희번득 뜬다","Eyes flash open",""],
  ["액체/물","뻘뻘","ppeolppeol","/p͈ʌlp͈ʌl/","땀을 많이 흘리는 모양","Sweating profusely","땀을 뻘뻘 흘린다","Sweating profusely",""],
  ["액체/물","그렁그렁","geureonggeureong","/ɡɯɾʌŋɡɯɾʌŋ/","눈물이 맺힌 모양","Tears welling up","눈물이 그렁그렁 맺혔다","Tears welled up",""],
  ["액체/물","글썽글썽","geulsseong-geulsseong","/kɯɭs͈ʌŋ kɯɭs͈ʌŋ/","눈물이 글썽거리는 모양","Eyes brimming with tears","눈물이 글썽글썽","Eyes brim with tears",""],
  ["액체/물","꿀렁꿀렁","kkulreongkkulreong","/k͈ulɾʌŋk͈ulɾʌŋ/","꿀렁거리는 모양","Stomach churning","뱃속이 꿀렁꿀렁","Stomach churns",""],
  ["액체/물","넘실넘실","neomsilneomsil","/nʌmsilnʌmsil/","넘실거리는 모양","Waves rolling","파도가 넘실넘실","Waves roll gently",""],
  ["액체/물","부슬부슬","buseulbuseul","/busɯlbusɯl/","가랑비가 내리는 모양","Drizzling rain","비가 부슬부슬 내린다","Rain drizzles",""],
  ["액체/물","사르르","sareureu","/saɾɯɾɯ/","사르르 녹는 모양","Melting smoothly","눈이 사르르 녹는다","Snow melts smoothly",""],
  ["액체/물","사르륵","sareureuk","/saɾɯɾɯk/","사르륵 녹는 모양","Melting away","설탕이 사르륵 녹는다","Sugar dissolves away",""],
  ["액체/물","일렁일렁","ilreongilreong","/ilɾʌŋilɾʌŋ/","물결이 넘실거리는 모양","Rippling","호수가 일렁일렁","Lake ripples",""],
  ["액체/물","찔끔찔끔","jjilkkeumjjilkkeum","/tɕ͈ilk͈ɯmtɕ͈ilk͈ɯm/","찔끔찔끔 흘리는 모양","Dripping little by little","피가 찔끔찔끔 난다","Blood drips little by little",""],
  ["액체/물","찰랑찰랑","chalrangchalrang","/tɕʰalɾaŋtɕʰalɾaŋ/","물결이 넘실거리는 모양","Splashing gently","물이 찰랑찰랑","Water splashes gently",""],
  ["액체/물","풀렁풀렁","pulreongpulreong","/pulɾʌŋpulɾʌŋ/","풀렁거리는 모양","Sloshing","물이 풀렁풀렁","Water sloshes",""],
  ["움직임/동작","빙글빙글/빙빙","binggeulbinggeul","/biŋɡɯlbiŋɡɯl/","회전하는 모양","Spinning around","빙글빙글 돌아가는 회전목마","Carousel spinning round and round",""],
  ["움직임/동작","깡충깡충","kkangchungkkangchung","/k͈aŋtɕʰuŋk͈aŋtɕʰuŋ/","뛰는 모양","Hopping or jumping","토끼가 깡충깡충 뛴다","Rabbit hops bounce bounce","hop hop"],
  ["움직임/동작","뒤뚱뒤뚱","dwittungdwittung","/dwit͈uŋdwit͈uŋ/","뒤뚱거리며 걷는 모양","Waddling","펭귄이 뒤뚱뒤뚱 걷는다","Penguin waddles side to side",""],
  ["움직임/동작","휘청휘청","hwicheonghwicheong","/hwitɕʰʌŋhwitɕʰʌŋ/","비틀거리는 모양","Staggering or swaying","술에 취해 휘청휘청","Staggering drunk",""],
  ["움직임/동작","성큼성큼","seongkeumseongkeum","/sʌŋkɯmsʌŋkɯm/","큰 걸음으로 걷는 모양","Striding with big steps","아버지가 성큼성큼 걸어오신다","Father strides with big steps",""],
  ["움직임/동작","어슬렁어슬렁","eoseulreongeoseulreong","/ʌsɯlɾʌŋʌsɯlɾʌŋ/","배회하는 모양","Wandering or loitering","고양이가 어슬렁어슬렁 다닌다","Cat wanders around lazily",""],
  ["움직임/동작","팔랑팔랑","palrangpalrang","/palɾaŋpalɾaŋ/","날갯짓하는 모양","Fluttering wings","나비가 팔랑팔랑 날아다닌다","Butterfly flutters its wings",""],
  ["움직임/동작","슬슬","seulseul","/sɯlsɯl/","천천히 움직이는 모양","Slowly or gradually","슬슬 집에 갈 시간이다","Time to slowly head home",""],
  ["움직임/동작","쏙/쑥","ssok","/s͈ok/","들어가거나 나오는 모양","Going in or out quickly","토끼가 굴 속으로 쏙 들어갔다","Rabbit went quickly into the burrow",""],
  ["움직임/동작","꾹꾹","kkukkkuk","/k͈uk͈kuk/","세게 누르는 모양","Pressing firmly","반죽을 꾹꾹 누른다","Pressing dough firmly",""],
  ["움직임/동작","쭉쭉","jjukjjuk","/tɕ͈uktɕ͈uk/","늘이는 모양","Stretching out","고무줄을 쭉쭉 늘인다","Stretching rubber band out",""],
  ["움직임/동작","갉작갉작","gakjak-gakjak","/kak̚t͡ɕak̚ kak̚t͡ɕak̚/","갉아먹는 소리/모양","Gnawing or nibbling","다람쥐가 도토리를 갉작갉작","Squirrel gnaws on acorn",""],
  ["움직임/동작","굽신굽신","gupsingupsin","/ɡupsiŋupsin/","허리를 굽히는 모양","Bowing repeatedly","허리를 굽신굽신 절한다","Bowing repeatedly at the waist",""],
  ["움직임/동작","굽실굽실","gupsilgupsil","/ɡupsilɡupsil/","허리를 굽히는 모양","Bowing politely","굽실굽실 인사한다","Greeting with polite bows",""],
  ["움직임/동작","까불까불","kkabulkkabul","/k͈abulk͈abul/","까불거리는 모양","Acting playfully","아이가 까불까불 장난친다","Child plays pranks mischievously",""],
  ["움직임/동작","껑충껑충","kkeongchungkkeongchung","/k͈ʌŋtɕʰuŋk͈ʌŋtɕʰuŋ/","껑충껑충 뛰는 모양","Leaping or bouncing","캥거루가 껑충껑충 뛴다","Kangaroo leaps and bounces",""],
  ["움직임/동작","꼬물꼬물","kkomulkkomul","/k͈omulk͈omul/","꼬물거리는 모양","Wriggling","애벌레가 꼬물꼬물","Caterpillar wriggles",""],
  ["움직임/동작","꼴딱꼴딱/꿀떡꿀떡","kkolttakkkolttak","/k͈olt͈ak͈kolt͈ak/","삼키는 모양","Gulping down","물을 꿀떡꿀떡 마신다","Gulping water down",""],
  ["움직임/동작","꼼지락꼼지락","kkomjirakkkomjirak","/k͈omtɕiɾak͈komtɕiɾak/","꼼지락거리는 모양","Fidgeting","손가락을 꼼지락꼼지락","Fidgeting with fingers",""],
  ["움직임/동작","꽉","kkwak","/k͈wak̚/","꽉 쥐는 모양","Gripping tightly","손을 꽉 잡았다","Gripped hand tightly",""],
  ["움직임/동작","꾸물럭꾸물럭","kkumulreokkkumulreok","/k͈umulɾʌk͈kumulɾʌk/","꾸물거리는 모양","Moving sluggishly","이불 속에서 꾸물럭꾸물럭","Wriggling sluggishly under blanket",""],
  ["움직임/동작","꾸벅꾸벅","kkubeokkkubeok","/k͈ubʌk͈kubʌk/","졸면서 머리를 숙이는 모양","Nodding off sleepily","졸려서 꾸벅꾸벅","Nodding off sleepily",""],
  ["움직임/동작","꿈틀꿈틀","kkumteulkkumteul","/k͈umtɯlk͈umtɯl/","꿈틀거리는 모양","Squirming or wriggling","지렁이가 꿈틀꿈틀","Earthworm squirms and wriggles",""],
  ["움직임/동작","나풀나풀","napulnapul","/napulnapul/","나풀거리며 날리는 모양","Fluttering down","꽃잎이 나풀나풀 떨어진다","Flower petals flutter down",""],
  ["움직임/동작","느릿느릿","neurit-neurit","/nɯɾit̚ nɯɾit̚/","느리게 움직이는 모양","Moving slowly","거북이가 느릿느릿 걷는다","Turtle walks slowly",""],
  ["움직임/동작","다르륵/드르륵","dareureuk","/daɾɯɾɯk/","빠르게 떨리거나 부딪히는 소리","Rattling sound","전화기가 드르륵 울린다","Phone rings with rattling sound",""],
  ["움직임/동작","달랑달랑","dalrangdalrang","/dalɾaŋdalɾaŋ/","매달려 흔들리는 모양","Dangling and swaying","열쇠가 달랑달랑 흔들린다","Keys dangle and sway",""],
  ["움직임/동작","더금더금","deogeumdeogeum","/dʌɡɯmdʌɡɯm/","더듬거리는 모양","Groping hesitantly","말을 더금더금 더듬는다","Stammering hesitantly",""],
  ["움직임/동작","더듬더듬","deodeumdeodeum","/dʌdɯmdʌdɯm/","더듬거리는 모양","Groping or fumbling","어둠 속을 더듬더듬 찾는다","Groping in the dark",""],
  ["움직임/동작","덜덜","deoldeol","/dʌldʌl/","떨리는 모양/소리","Shivering or trembling","추워서 덜덜 떨린다","Shivering from cold",""],
  ["움직임/동작","덥석","deopseok","/dʌpsʌk/","덥석 물거나 잡는 모양","Grabbing suddenly","먹이를 덥석 물었다","Grabbed prey suddenly",""],
  ["움직임/동작","덩실덩실","deongsildeongsil","/dʌŋsildʌŋsil/","춤추며 움직이는 모양","Dancing joyfully","춤을 덩실덩실 춘다","Dancing joyfully",""],
  ["움직임/동작","데굴데굴","deguldegul","/deɡuldeɡul/","구르는 모양","Rolling around","공이 데굴데굴 구른다","Ball rolls tumbling","roll roll"],
  ["움직임/동작","도리도리","doridori","/doɾidoɾi/","머리를 좌우로 흔드는 모양","Shaking head side to side","아기가 도리도리 머리를 흔든다","Baby shakes head side to side",""],
  ["움직임/동작","두리번두리번","duribeonduribeon","/duɾibʌnduɾibʌn/","두리번거리는 모양","Looking around","고개를 두리번두리번","Looking around searchingly",""],
  ["움직임/동작","둘둘","duldul","/duldul/","돌돌 감는 모양","Winding or wrapping","실을 둘둘 감는다","Winding thread round and round",""],
  ["움직임/동작","들썩들썩","deulsseokdeulsseok","/dɯls͈ʌkdɯls͈ʌk/","들썩거리는 모양","Bouncing or swaying","어깨가 들썩들썩 춤을 춘다","Shoulders bounce while dancing",""],
  ["움직임/동작","또르르","ttoreureu","/t͈oɾɯɾɯ/","또르르 구르는 모양","Rolling smoothly","구슬이 또르르 굴러간다","Marble rolls smoothly",""],
  ["움직임/동작","만지작만지작","manjijakmanjijak","/mantɕitɕakmantɕitɕak/","만지는 모양","Fiddling with","동전을 만지작만지작","Fiddling with coin",""],
  ["움직임/동작","머뭇머뭇","meomutmeomut","/mʌmutmʌmut/","머뭇거리는 모양","Hesitating","머뭇머뭇 망설인다","Hesitating uncertainly",""],
  ["움직임/동작","멈칫멈칫","meomchitmeomchit","/mʌmtɕʰitmʌmtɕʰit/","멈칫거리는 모양","Faltering or pausing","멈칫멈칫 주저한다","Faltering and pausing",""],
  ["움직임/동작","바둥바둥/바동바동","badungbadung","/baduŋbaduŋ/","발버둥치는 모양","Struggling or kicking","아기가 바둥바둥 발버둥","Baby kicks and struggles",""],
  ["움직임/동작","바드득/파드득/빠드득","badeudeuk","/badɯdɯk/","세게 누르는 소리","Grinding or clenching","이를 바드득 갈았다","Grinding teeth with sound",""],
  ["움직임/동작","바들바들/부들부들","badeulbadeul","/badɯlbadɯl/","떨리는 모양","Shivering with cold","추워서 바들바들 떨린다","Trembling from cold",""],
  ["움직임/동작","바르르","bareureu","/baɾɯɾɯ/","떨리는 모양","Trembling slightly","입술이 바르르 떨린다","Lips tremble slightly",""],
  ["움직임/동작","바르르/부르르/푸르르","bareureu","/baɾɯɾɯ/","떨리는 모양","Shivering or trembling","몸이 부르르 떨린다","Body shivers",""],
  ["움직임/동작","박박","bakbak","/bakbak/","긁는 소리/모양 (박을 긁는 느낌)","Scrubbing hard","때를 박박 밀었다","Scrubbed dirt hard",""],
  ["움직임/동작","벌딱벌딱/불똑불똑","beolttakbeolttak","/bʌlt͈akbʌlt͈ak/","갑자기 일어나는 모양","Getting up suddenly","벌딱 일어났다","Got up suddenly",""],
  ["움직임/동작","벌떡/발딱/팔딱/빨딱","beoltteok","/bʌlt͈ʌk/","갑자기 일어나는 모양","Jumping up suddenly","벌떡 일어나 뛰어갔다","Jumped up suddenly and ran",""],
  ["움직임/동작","보듬보듬/부둥부둥","bodeumbodeum","/bodɯmbodɯm/","보듬는 모양","Embracing or hugging","아기를 보듬보듬 안는다","Embracing baby gently",""],
  ["움직임/동작","부들부들","budeulbudeul","/budɯlbudɯl/","부들부들 떨리는 모양","Trembling","화가 나서 부들부들 떨린다","Trembling with anger",""],
  ["움직임/동작","부랴부랴","burya-burya","/puɾja puɾja/","급히 서두르는 모양 (불이야, 불이야에서 파생)","Hurrying frantically","부랴부랴 뛰어갔다","Rushed off frantically",""],
  ["움직임/동작","붕방붕방","bungbangbungbang","/buŋbaŋbuŋbaŋ/","붕붕 날아다니는 모양","Flying around","벌이 붕방붕방 날아다닌다","Bee flies around buzzing",""],
  ["움직임/동작","비실비실","bisilbisil","/bisilbisil/","힘없이 움직이는 모양","Moving weakly","힘없이 비실비실 걷는다","Walking weakly without strength",""],
  ["움직임/동작","비틀비틀","biteulbiteul","/bitɯlbitɯl/","비틀거리는 모양","Staggering","술에 취해 비틀비틀","Staggering drunk",""],
  ["움직임/동작","빌빌","bilbil","/bilbil/","기운 없이 돌아다니는 모양","Wandering aimlessly","빌빌 돌아다니지 마라","Don't wander around aimlessly",""],
  ["움직임/동작","빨빨","ppalppal","/p͈alp͈al/","바쁘게 움직이는 모양","Moving busily","바쁘게 빨빨 뛰어다닌다","Running around busily",""],
  ["움직임/동작","뽈랑뽈랑","ppolrangppolrang","/p͈olɾaŋp͈olɾaŋ/","바삐 걸어다니는 모양","Walking briskly","아이가 뽈랑뽈랑 뛰어간다","Child runs briskly",""],
  ["움직임/동작","삐질삐질","ppijilppijil","/p͈itɕilp͈itɕil/","땀이 배어나오는 모양","Sweating profusely","땀이 삐질삐질 난다","Sweating profusely",""],
  ["움직임/동작","사박사박","sabaksabak","/sabaksabak/","사박사박 걷는 소리","Walking on snow","눈길을 사박사박 걷는다","Walking on snowy path with crunching",""],
  ["움직임/동작","사부작","sabujak","/sabutɕak/","사부작 움직이는 모양","Moving stealthily and quietly","살금살금 사부작 다가간다","Approaching stealthily and quietly",""],
  ["움직임/동작","사붓사붓","sabutsabut","/sabutsabut/","사뿐사뿐 걷는 모양","Walking quietly","살금살금 사붓사붓 걷는다","Walking quietly and stealthily",""],
  ["움직임/동작","사뿐사뿐","sappun-sappun","/sap͈un sap͈un/","가볍게 걷는 모양","Walking lightly","발레리나가 사뿐사뿐 춤춘다","Ballerina dances lightly",""],
  ["움직임/동작","살금살금","salgeumsalgeum","/salɡɯmsalɡɯm/","살금살금 조심히 움직이는 모양","Moving stealthily","도둑고양이가 살금살금","Stray cat sneaks quietly",""],
  ["움직임/동작","살금살금/슬금슬금","salgeumsalgeum","/salɡɯmsalɡɯm/","살금살금 움직이는 모양","Sneaking quietly","살금살금 다가간다","Approaching stealthily",""],
  ["움직임/동작","시드럭시드럭","sideureoksideureok","/sidɯɾʌksidɯɾʌk/","시들어가는 모양","Wilting gradually","꽃이 시드럭시드럭 시든다","Flower wilts gradually",""],
  ["움직임/동작","시들시들","sideulsideul","/sidɯlsidɯl/","시들어가는 모양","Withering","더위에 식물이 시들시들","Plant withers in the heat",""],
  ["움직임/동작","아기작아기작","agijakagijak","/aɡitɕakaɡitɕak/","아기가 걷는 모양","Baby toddling","아기가 아기작아기작 걷는다","Baby toddles with tiny steps",""],
  ["움직임/동작","아장아장","ajangajang","/atɕaŋatɕaŋ/","아기가 걷는 모양","Toddling like baby","아기가 아장아장 첫걸음","Baby takes first toddling steps",""],
  ["움직임/동작","야금야금","yageumyageum","/jaɡɯmjaɡɯm/","야금야금 갉는 모양","Nibbling bit by bit","야금야금 조금씩 먹는다","Nibbling bit by bit",""],
  ["움직임/동작","엉금엉금","eonggeumeonggeum","/ʌŋɡɯmʌŋɡɯm/","엉금엉금 기어가는 모양","Crawling slowly","거북이가 엉금엉금 기어간다","Turtle crawls slowly",""],
  ["움직임/동작","엉기적엉기적","eonggijeokeonggijeok","/ʌŋɡitɕʌkʌŋɡitɕʌk/","느릿느릿 걷는 모양","Walking slowly","느릿느릿 엉기적엉기적","Moving slowly and sluggishly",""],
  ["움직임/동작","오물오물","omulomul","/omulomul/","오물거리며 씹는 모양","Chewing with mouth closed","입을 오물오물 씹는다","Chewing with mouth closed",""],
  ["움직임/동작","우르르","ureureu","/uɾɯɾɯ/","우르르 몰려가는 모양","Rushing together","사람들이 우르르 몰려갔다","People rushed together in a crowd",""],
  ["움직임/동작","움직움직","umjikumjik","/umtɕikumtɕik/","움직이는 모양","Moving slightly","살금살금 움직움직","Moving stealthily little by little",""],
  ["움직임/동작","움찔움찔","umjjilumjjil","/umtɕ͈ilumtɕ͈il/","움찔거리는 모양","Flinching repeatedly","무서워서 움찔움찔","Flinching repeatedly in fear",""],
  ["움직임/동작","잘금잘금","jalgeumjalgeum","/tɕalɡɯmtɕalɡɯm/","잘금잘금 씹는 모양","Chewing small bites","과자를 잘금잘금 씹는다","Chewing snack in small bites",""],
  ["움직임/동작","절뚝절뚝","jeolttukjeolttuk","/tɕʌlt͈uktɕʌlt͈uk/","절뚝거리며 걷는 모양","Limping","다리를 다쳐 절뚝절뚝","Limping with injured leg",""],
  ["움직임/동작","종종걸음","jongjonggeoleum","/tɕoŋtɕoŋɡʌlɯm/","종종걸음으로 걷는 모양","Walking with quick short steps","종종걸음으로 뛰어간다","Running with quick short steps",""],
  ["움직임/동작","주물럭주물럭","jumulreokjumulreok","/tɕumulɾʌktɕumulɾʌk/","주무르는 모양","Kneading or massaging","반죽을 주물럭주물럭","Kneading dough thoroughly",""],
  ["움직임/동작","주섬주섬","juseomjuseom","/tɕusʌmtɕusʌm/","물건을 주워 모으는 모양","Gathering items carefully","짐을 주섬주섬 챙긴다","Gathering belongings carefully",""],
  ["움직임/동작","철푸덕","cheolpudeok","/tɕʰʌlpudʌk/","날갯짓 소리","Flapping heavily","새가 철푸덕 날아오른다","Bird flies up flapping heavily",""],
  ["움직임/동작","첨벙첨벙","cheombeongcheombeong","/tɕʰʌmbʌŋtɕʰʌmbʌŋ/","물에 뛰어드는 소리","Splashing into water","물속으로 첨벙첨벙 뛰어들었다","Jumped splashing into water",""],
  ["움직임/동작","총총","chongchong","/tɕʰoŋtɕʰoŋ/","총총히 걷는 모양","Walking quickly","총총히 걸어간다","Walking quickly",""],
  ["움직임/동작","쿡","kuk","/kuk/","쿡 찌르는 모양","Poking or stabbing","옆구리를 쿡 찔렀다","Poked side sharply",""],
  ["움직임/동작","파닥","padak","/padak/","날갯짓 소리","Flapping wings","새가 파닥파닥 날갯짓","Bird flaps wings",""],
  ["움직임/동작","팔짝/펄쩍","paljjak","/paltɕ͈ak/","뛰어오르는 모양","Jumping up","펄쩍 뛰어올랐다","Jumped up high",""],
  ["움직임/동작","펄럭","peolreok","/pʌlɾʌk/","펄럭이는 모양","Flapping or fluttering","깃발이 펄럭펄럭 휘날린다","Flag flutters in the wind",""],
  ["움직임/동작","폴폴/풀풀","polpol","/polpol/","날리는 모양","Floating or flying lightly","가루가 폴폴 날린다","Powder floats lightly in air",""],
  ["움직임/동작","푸드덕","pudeudeok","/pudɯdʌk/","날갯짓 소리","Fluttering noisily","닭이 푸드덕 날개를 친다","Chicken flaps wings noisily",""],
  ["움직임/동작","풀썩풀썩","pulsseokpulsseok","/puls͈ʌkpuls͈ʌk/","풀썩 주저앉는 모양","Collapsing or slumping","풀썩 주저앉았다","Slumped down",""],
  ["움직임/동작","허겁지겁","heogeop-jigeop","/hʌɡʌp̚ t͡ɕiɡʌp̚/","허겁지겁 서두르는 모양","Rushing frantically","허겁지겁 밥을 먹는다","Eating frantically",""],
  ["움직임/동작","허덕지덕","heodeokjideok","/hʌdʌktɕidʌk/","허덕거리는 모양","Panting heavily","숨을 허덕지덕 쉰다","Panting heavily",""],
  ["움직임/동작","허둥지둥","heodungjidung","/hʌduŋtɕiduŋ/","허둥지둥 서두르는 모양","Rushing confusedly","허둥지둥 서두른다","Rushing about confusedly",""],
  ["움직임/동작","허우적허우적","heoujeokheoujeok","/hʌutɕʌkhʌutɕʌk/","허우적거리는 모양","Floundering","물속에서 허우적허우적","Floundering in water",""],
  ["움직임/동작","홀짝홀짝","holjjakholjjak","/holtɕ͈akholtɕ͈ak/","홀짝거리는 모양","Sipping","차를 홀짝홀짝 마신다","Sipping tea",""],
  ["움직임/동작","활활/훨훨/훌훌","hwalhwal","/hwalhwal/","불이 타오르거나 날개짓하는 모양","Blazing or flying gracefully","새가 훨훨 날아간다","Bird flies away gracefully",""],
  ["움직임/동작","후비적후비적","hubijeokhubijeok","/hubitɕʌkhubitɕʌk/","후비는 모양","Picking at","코를 후비적후비적","Picking at nose",""],
  ["움직임/동작","흔드적흔드적","heundeujeokheundeujeok","/hɯndɯtɕʌkhɯndɯtɕʌk/","흔들거리는 모양","Swaying loosely","꼬리를 흔드적흔드적","Wagging tail loosely",""],
  ["움직임/동작","흔들흔들","heundeulheundeul","/hɯndɯlhɯndɯl/","흔들리는 모양","Shaking or swinging","나무가 바람에 흔들흔들","Tree swings in the wind",""],
  ["음식/식감","고슬고슬","goseulgoseul","/ɡosɯlɡosɯl/","밥알이 적당히 익은 모양","Perfectly cooked rice fluffy","밥이 고슬고슬 잘 되었다","Rice cooked perfectly fluffy",""],
  ["자연현상","뉘엿뉘엿","nwiyut-nwiyut","/nɥijʌt̚ nɥijʌt̚/","해가 뉘엿뉘엿 지는 모양","Sun setting slowly","해가 뉘엿뉘엿 진다","Sun sets slowly",""],
  ["자연현상","산들산들","sandeulsandeul","/sandɯlsandɯl/","산들바람이 부는 모양","Gentle breeze blowing","바람이 산들산들 분다","Breeze blows gently",""],
  ["작업/행위","구기적구기적","gugijeokgugijeok","/ɡuɡitɕʌkɡuɡitɕʌk/","구기는 모양","Crumpling up","종이를 구기적구기적","Crumpling paper repeatedly",""],
  ["작업/행위","끄적끄적","kkeujeokkkeujeok","/k͈ɯtɕʌk͈kɯtɕʌk/","글씨를 쓰는 모양","Scribbling or jotting","일기를 끄적끄적 쓴다","Scribbling diary entry",""],
  ["작업/행위","뚝딱","ttukttak","/t͈ukt͈ak/","뚝딱 만드는 모양","Making quickly","뚝딱 만들었다","Made it quickly",""],
  ["촉감/질감","끈적끈적/끈끈","kkeunjeokkkeunjeok","/k͈ɯntɕʌk͈kɯntɕʌk/","끈적거리는 느낌","Sticky or gooey texture","손이 끈적끈적하다","Hands are sticky",""],
  ["촉감/질감","딱딱","ttakttak","/t͈akt͈ak/","단단한 느낌","Hard or stiff texture","빵이 딱딱하게 굳었다","Bread hardened stiff",""],
  ["촉감/질감","푹신푹신","puksinpuksin","/puksinpuksin/","폭신한 느낌","Soft and fluffy","침대가 푹신푹신하다","Bed is soft and fluffy",""],
  ["촉감/질감","퍽퍽","peokpeok","/pʌkpʌk/","수분이 없고 퍽퍽한 느낌","Dry and crumbly","고구마가 퍽퍽하다","Sweet potato is dry and crumbly",""],
  ["촉감/질감","흠뻑/흥건","heumppeok","/hɯmp͈ʌk/","많이 젖은 모양","Thoroughly soaked","비에 흠뻑 젖었다","Got thoroughly soaked in rain",""],
  ["촉감/질감","거칠거칠","geochilgeochil","/ɡʌtɕʰilɡʌtɕʰil/","거친 느낌","Rough texture","손이 거칠거칠하다","Hands are rough",""],
  ["촉감/질감","고들고들","godeulgodeul","/ɡodɯlɡodɯl/","적당히 마른 느낌","Properly dried or crisp","김치가 고들고들 맛있다","Kimchi is properly fermented and crisp",""],
  ["촉감/질감","곱실곱실","gopsilgopsil","/ɡopsilɡopsil/","곱슬곱슬한 모양","Curly or wavy","머리카락이 곱실곱실","Hair is curly and wavy",""],
  ["촉감/질감","굽슬굽슬","gupseulgupseul","/ɡupsɯlɡupsɯl/","곱슬곱슬한 모양","Curly or wavy hair","파마머리가 굽슬굽슬","Permed hair is wavy",""],
  ["촉감/질감","까끌까끌","kkakkeulkkakkeul","/k͈ak͈ɯlk͈ak͈ɯl/","까끌까끌한 느낌","Scratchy or rough","턱수염이 까끌까끌","Beard is scratchy",""],
  ["촉감/질감","까슬까슬","kkaseulkkaseul","/k͈asɯlk͈asɯl/","까슬까슬한 느낌","Slightly rough","수건이 까슬까슬","Towel is slightly rough",""],
  ["촉감/질감","까칠까칠","kkachilkkachil","/k͈atɕʰilk͈atɕʰil/","까칠한 느낌","Rough or prickly","피부가 까칠까칠","Skin is rough and prickly",""],
  ["촉감/질감","꾸덕꾸덕","kkudeokkkudeok","/k͈udʌk͈kudʌk/","적당히 마른 느낌","Thick and sticky consistency","요거트가 꾸덕꾸덕","Yogurt is thick and creamy",""],
  ["촉감/질감","말랑말랑","malrangmalrang","/malɾaŋmalɾaŋ/","말랑한 느낌","Soft and squishy","떡이 말랑말랑하다","Rice cake is soft and squishy",""],
  ["촉감/질감","묵직묵직","mukjikmukjik","/muktɕikmuktɕik/","무겁고 단단한 느낌","Heavy and solid","돌이 묵직묵직하다","Stone is heavy and solid",""],
  ["촉감/질감","물렁물렁","mulreongmulreong","/mulɾʌŋmulɾʌŋ/","무른 느낌","Soft or mushy","복숭아가 물렁물렁 익었다","Peach ripened soft and mushy",""],
  ["촉감/질감","물렁물렁","mulreongmulreong","/mulɾʌŋmulɾʌŋ/","무른 느낌","Soft or mushy","복숭아가 물렁물렁 익었다","Peach ripened soft and mushy",""],
  ["촉감/질감","말캉말캉","malkangmalkang","/malkaŋmalkaŋ/","말랑하고 물렁한 느낌 (물에서 파생)","Soft and pliable","젤리가 말캉말캉","Jelly is soft and pliable",""],
  ["촉감/질감","미끄덩","mikkeudeong","/mik͈ɯdʌŋ/","미끄러지는 모양","Slippery","비누가 미끄덩 미끄럽다","Soap is slippery",""],
  ["촉감/질감","미끈미끈","mikkeunmikkeun","/mik͈ɯnmik͈ɯn/","매끄러운 느낌","Smooth and slippery","로션을 바르니 미끈미끈","Lotion feels smooth and slippery",""],
  ["촉감/질감","미끌미끌","mikkeulmikkeul","/mik͈ɯlmik͈ɯl/","미끄러운 느낌","Very slippery","빙판이 미끌미끌","Ice is very slippery",""],
  ["촉감/질감","바삭","basak","/basak/","바삭한 느낌","Crispy or crunchy","과자가 바삭바삭","Snacks are very crispy","crunch / crisp"],
  ["촉감/질감","바삭/퍼석","basak","/basak/","바삭한 느낌","Crispy texture","비스킷이 바삭하다","Biscuit is crispy",""],
  ["촉감/질감","바삭바삭","basakbasak","/basakbasak/","바삭한 느낌","Very crispy","치킨이 바삭바삭","Chicken is crispy","crunch crunch"],
  ["촉감/질감","보들보들","bodeulbodeul","/bodɯlbodɯl/","부드러운 느낌","Soft and smooth","아기 피부가 보들보들","Baby skin is soft and smooth",""],
  ["촉감/질감","부드럽게","budeureopge","/budɯɾʌpɡe/","부드럽게","Softly or gently","크림이 부드럽게 발린다","Cream applies smoothly",""],
  ["촉감/질감","진득진득","jindeukjindeuk","/tɕindɯktɕindɯk/","끈적이는 느낌","Very sticky or viscous","아교가 진득진득","Glue is very sticky",""],
  ["촉감/질감","질퍽질퍽","jilpeokjilpeok","/tɕilpʌktɕilpʌk/","질척한 느낌","Muddy or soggy","진흙이 질퍽질퍽","Mud is soggy",""],
  ["촉감/질감","쫀득쫀득","jjondeukjjondeuk","/tɕ͈ondɯktɕ͈ondɯk/","쫀득한 느낌","Chewy and sticky","떡볶이가 쫀득쫀득","Tteokbokki is chewy and sticky",""],
  ["촉감/질감","쫄깃쫄깃","jjolgitjjolgit","/tɕ͈olɡittɕ͈olɡit/","쫄깃한 느낌","Chewy or springy texture","면이 쫄깃쫄깃","Noodles are chewy and springy",""],
  ["촉감/질감","촉촉촉","chokchokchok","/tɕʰoktɕʰoktɕʰok/","촉촉한 느낌","Moist feeling","피부가 촉촉촉","Skin feels moist",""],
  ["촉감/질감","촉촉하게","chokchokhage","/tɕʰoktɕʰokhaɡe/","촉촉하게","Texture description","피부를 촉촉하게 관리한다","Maintaining skin moistly",""],
  ["촉감/질감","치덕치덕","chideokchideok","/tɕʰidʌktɕʰidʌk/","끈적끈적 붙은 모양","Stickily attached","손에 풀이 치덕치덕","Paste sticks to hands",""],
  ["촉감/질감","탱글탱글","taenggeultaenggeul","/tɛŋɡɯltɛŋɡɯl/","탱탱한 느낌","Bouncy and firm","피부가 탱글탱글","Skin is bouncy and firm",""],
  ["촉감/질감","탱탱하게","taengtaenghage","/tɛŋtɛŋhaɡe/","탱탱하게","Texture description","피부가 탱탱하게 팽팽하다","Skin is taut and firm",""],
  ["촉감/질감","포근포근","pogeunpogeun","/poɡɯnpoɡɯn/","포근한 느낌","Warm and cozy","이불이 포근포근","Blanket is warm and cozy",""],
  ["촉감/질감","포슬포슬","poseulposeul","/posɯlposɯl/","포슬포슬한 느낌","Fluffy and dry","감자가 포슬포슬 익었다","Potato cooked fluffy",""],
  ["통증/신체반응","시큰시큰","sikeunsikeun","/sikɯnsikɯn/","은근히 아픈 느낌","Dull aching pain","무릎이 시큰시큰 아프다","Knee aches dully",""],
  ["통증/신체반응","욱신욱신","uksinuksin","/uksinuksin/","욱신거리며 아픈 느낌","Throbbing pain","상처가 욱신욱신","Wound throbs",""],
  ["통증/신체반응","아릿아릿","arit-arit","/aɾit̚ aɾit̚/","아리게 아픈 느낌","Stinging sensation","혀가 아릿아릿하다","Tongue stings",""],
  ["통증/신체반응","저릿저릿","jeorit-jeorit","/t͡ɕʌɾit̚ t͡ɕʌɾit̚/","저리게 아픈 느낌","Tingling or numbness","손이 저릿저릿하다","Hand tingles with numbness",""],
  ["통증/신체반응","찌르르르","jjireureureu","/tɕ͈iɾɯɾɯɾɯ/","찌르는 듯한 느낌이 퍼지는 모양","Sharp piercing sensation","전기가 찌르르르","Electric shock piercing",""],
  ["통증/신체반응","찌릿찌릿","jjirit-jjirit","/t͡ɕ͈iɾit̚ t͡ɕ͈iɾit̚/","찌르는 듯한 느낌","Electric or prickling sensation","어깨가 찌릿찌릿","Shoulder prickles",""],
  ["기타","땍꿍","ttaekkkung","/t͈ɛk͈kuŋ/","땍꿍 놀이 (모음 ㅐ 사용 신조어)","Peek-a-boo game","아기와 땍꿍 놀이","Playing peek-a-boo with baby",""],
  ["기타","아리랑","arirang","/aɾiɾaŋ/","아리랑","Arirang Korean folk song","아리랑 아리랑 아라리요","Arirang Arirang Arariyo Korean folk song",""],
  ["추가","아롱다롱","","","","","","",""],
  ["추가","우르르쾅쾅","","","","","","",""],
  ["추가","바스락바스락","","","","","","",""],
  ["추가","궁시렁궁시렁","","","","","","",""],
];

export const SOUNDS: SoundEntry[] = RAW.map(([cat,word,romaja,ipa,descKo,descEn,exKo,exEn,en]) => ({ cat, word, romaja, ipa, descKo, descEn, exKo, exEn, en }));

// category order (by count, biggest first) preserved from source
export const CAT_ORDER: string[] = ["감정/심리","동물 소리","말/대화","맛/냄새","모양/형태","빛/색깔","사람 소리","상태/정도","소리","시선/눈","액체/물","움직임/동작","음식/식감","자연현상","작업/행위","촉감/질감","통증/신체반응","기타","추가"];
